package pirateborg

import "fmt"

// 1-20 sailor, all else has one entry
var backgrounds = map[string]string{"sailor": "2d6 x 10s & a reason to go to sea",
	"actor":              "2d6 x 10s & a play or book",
	"apothecary":         "2d6 x 10s & healing kit",
	"artist":             "2d6 x 10s & art supplies",
	"assassin":           "2d6 x 10s & a dagger",
	"bandit":             "2d6 x 10s & a club",
	"barkeep":            "2d6 x 10s & a flask of fine rum",
	"blacksmith":         "2d6 x 10s & a set of files and tools",
	"bosun":              "2d6 x 10s & the respect of some crew",
	"business man":       "3d6 x 10s & a profitable past",
	"cabin boy":          "2d4 x 10s & a small toy or trinket",
	"captain":            "2d8 x 10s & a spyglass",
	"former captive":     "2d4 x 10s & your freedom",
	"castaway":           "2d4 x 10s & a keepsake from the island",
	"chef":               "2d6 x 10s & a book of recipes",
	"cook":               "2d6 x 10s & some fine cooking spices",
	"craftsman":          "2d6 x 10s & a set of tools",
	"criminal":           "1d10 x 10s & lockpick or a crowbar",
	"cultist":            "2d6 x 10s & a book of scripture",
	"deserter":           "2d4 x 10s & a small bounty on your head",
	"doctor":             "2d6 x 10s & a medical kit",
	"explorer":           "2d6 x 10s & a map and compass",
	"farmer":             "2d4 x 10s & a reason to leave your farm",
	"first mate":         "2d6 x 10s & a loyal friend",
	"gambler":            "1d12 x 10s & a sizable debt",
	"grave robber":       "2d6 x 10s & something from a corpse",
	"guard":              "2d6 x 10s & a keen eye for mischief",
	"gunner":             "2d6 x 10s & skill at shooting",
	"harlot":             "2d8 x 10s & an admirer and syphilis",
	"heretic":            "2d4 x 10s & a blasphemous disposition",
	"homemaker":          "2d6 x 10s & a loved one back home",
	"hunter":             "2d6 x 10s & a hunting knife",
	"former servant":     "2d4 x 10s & someone looking for you",
	"innkeeper":          "3d4 x 10s & a small inn somewhere",
	"landowner":          "3d6 x 10s & property somewhere",
	"loner":              "2d6 x 10s & a dislike of others",
	"cartographer":       "2d6 x 10s & map making tools",
	"marine":             "2d6 x 10s & a military cutlass",
	"medic":              "2d6 x 10s & a medical kit",
	"merchant":           "2d8 x 10s & good negotiating skills",
	"military":           "2d6 x 10s & combat training",
	"missionary":         "2d4 x 10s & a holy symbol and scripture",
	"monk":               "2d6 x 10s & a holy symbol and scripture",
	"musician":           "2d6 x 10s & [roll on instrument table, pg. 27]",
	"naval deserter":     "2d4 x 10s & a price on your head",
	"navigator":          "2d6 x 10s & a compass",
	"noble":              "3d6 x 10s & good manners",
	"nobody":             "2d4 x 10s & a desire for a purpose",
	"nurse":              "2d6 x 10s & a medical kit",
	"officer":            "2d8 x 10s & a cutlass and military training",
	"orphan":             "2d4 x 10s & a longing for new parental figures",
	"performer":          "2d6 x 10s & [roll on instrument table, pg. 27]",
	"philosopher":        "2d6 x 10s & a book and a puzzling disposition",
	"pilot":              "2d6 x 10s & a compass",
	"pirate":             "2d6 x 10s & an empty bottle of rum",
	"politician":         "2d6 x 10s & skill at deception",
	"priest":             "2d6 x 10s & a holy symbol and scripture",
	"privateer":          "2d6 x 10s & a letter of marque",
	"quartermaster":      "2d6 x 10s & the respect of a ship's crew",
	"refugee":            "2d4 x 10s & strong survival instincts",
	"religious follower": "2d4 x 10s & a strong sense of faith",
	"revolutionary":      "2d6 x 10s & bold plans and a few allies",
	"rumored sorcerer":   "2d6 x 10s & dark and powerful knowledge",
	"runaway":            "2d4 x 10s & a desire for a new home",
	"sail maker":         "2d6 x 10s & skill with sails",
	"scholar":            "2d6 x 10s & a few books",
	"scoundrel":          "2d8 x 10s & a few enemies along the way",
	"scout":              "2d6 x 10s & keen senses and a map",
	"shaman":             "2d4 x 10s & herbs and mystic knowledge",
	"shipwright":         "2d6 x 10s & skill with woodworking",
	"smuggler":           "2d6 x 10s & a bounty on your head",
	"soldier":            "2d6 x 10s & a tactical mind",
	"spy":                "2d6 x 10s & a dark cloak",
	"student":            "2d4 x 10s & a strong will to learn",
	"surgeon":            "2d6 x 10s & a medical kit",
	"thief":              "1d12 x 10s & lockpicks",
	"vagabond":           "2d4 x 10s & a leather backpack",
	"victim":             "2d6 x 10s & a haunted past",
	"warrior":            "2d4 x 10s & a cultural weapon",
	"whaler":             "2d6 x 10s & a harpoon",
	"writer":             "2d6 x 10s & ink, quills, and parchment",
}

var loot = map[string]string{
	"00":    "Roll again twice.",
	"01-20": "The result on the Ancient Relics table (pg. 62).",
	"21":    B("Skull with glowing green sockets."),
	"22":    fmt.Sprintf("%s (d6).", B("A nasty-looking knife")),
	"23":    B("Wanted poster with a picture of one of the PCs on it."),
	"24":    fmt.Sprintf("%s %s", B("Black candle."), I("When lit, its purple flame forms a skull.")),
	"25":    B("Single golden manacle with 5 links."),
	"26":    fmt.Sprintf("%s %s", B("A leather journal"), I("containing 1 sea shanty (pg. 68).")),
	"27":    fmt.Sprintf("%s %s", B("Oil lantern filled with dark green liquid."), I("It burns a pale green light for 5 feet but never runs out.")),
	"28":    B("Fine metal flask."),
	"29":    B("Bag of white powder."),
	"30":    fmt.Sprintf("%s %s", B("Small box with d12 black pearls"), I("worth a fortune.")),
	"31":    B("Sea shell lined with mother of pearl."),
	"32":    fmt.Sprintf("%s %s", B("Pipe carved out of whale bone."), I("A mysterious map is carved in the bowl.")),
	"33":    B("Dead rat."),
	"34":    fmt.Sprintf("%s %s", B("Jewel-encrusted egg."), I("Agility DR18 to open, or it breaks. Clockwork inside is worth 500s.")),
	"35":    fmt.Sprintf("%s %s", B("d8 crab claws."), I("Throwing them before casting a ritual lowers the DR by 1.")),
	"36":    B("Stone ring with an engraved rune."),
	"37":    fmt.Sprintf("%s %s", B("Deep blue gemstone."), I("It sparkles in the moonlight.")),
	"38":    fmt.Sprintf("%s %s", B("Obsidian figurine of a Kraken."), I("The Kraken won’t attack you.")),
	"39":    fmt.Sprintf("%s %s", B("Parrot feather."), I("+1 Devil's Luck each dawn.")),
	"40":    B("Some rotten dried fruit."),
	"41":    fmt.Sprintf("%s %s", B("Recipe for turtle stew."), I("If made, everyone who smells it passes out. At sea, the crew awakens with their ship drifting near a mysterious island.")),
	"42":    B("Small book on tying sailor knots."),
	"43":    fmt.Sprintf("%s %s", B("Deck of playing cards."), I("The queens are mermaids.")),
	"44":    B("Random bomb (pg. 53)."),
	"45":    fmt.Sprintf("%s %s", B("Jar of d10 eyeballs preserved in white rum."), I("They still see.")),
	"46":    B("Set of lock picks."),
	"47":    B("Paper doll painted with blood."),
	"48":    fmt.Sprintf("%s %s", B("Deep green gemstone"), I("worth 100s.")),
	"49":    B("Small wooden flute."),
	"50":    "50s.",
	"51":    "51s.",
	"52":    "52s.",
	"53":    "53s.",
	"54":    "54s.",
	"55":    "55s.",
	"56":    "56s.",
	"57":    "57s.",
	"58":    "58s.",
	"59":    "59s.",
	"60":    fmt.Sprintf("%s %s", B("Leather eye patch."), I("That eye can see in the dark.")),
	"61":    B("Flintlock pistol with tally marks."),
	"62":    B("d4 gold teeth."),
	"63":    B("Letter from a bonnie lass."),
	"64":    fmt.Sprintf("%s %s", B("A ship's schedule"), I("with details of a treasure ship.")),
	"65":    B("Jar of black sand."),
	"66":    fmt.Sprintf("%s %s", B("Book of dark rituals."), I("Test Spirit DR14 to learn one random ritual (pg. 64), or else permanently lose 1 Spirit.")),
	"67":    B("Handwritten collection of ghost stories."),
	"68":    fmt.Sprintf("%s %s", B("Book:"), B(I("A Guide to Sailor Tattoos."))),
	"69":    B("A live rat."),
	"70":    B("d4 dead fish."),
	"71":    fmt.Sprintf("%s %s", B("Vial of blowfish poison."), I("Test Toughness DR12 or take d10 damage.")),
	"72":    B("Treasure map (pg. 119)."),
	"73":    fmt.Sprintf("%s %s", B("A glass eye"), I("that always looks West.")),
	"74":    B("Broken cutlass hilt (d4)."),
	"75":    fmt.Sprintf("%s (3d4), %s", B("Glass dagger"), I("breaks after 1 use.")),
	"76":    fmt.Sprintf("%s %s", B("Book: The Secret Art of Fencing in the Age of Gunpowder."), I("Test Presence DR12 to permanently gain +1 Strength. It only works once.")),
	"77":    B("Bottle filled with iridescent dust."),
	"78":    fmt.Sprintf("%s %s", B("Lint."), I("Flammable.")),
	"79":    fmt.Sprintf("%s %s", B("Golden idol."), I("Priceless, belongs in a museum.")),
	"80":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 80s")),
	"81":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 81s")),
	"82":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 82s")),
	"83":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 83s")),
	"84":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 84s")),
	"85":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 85s")),
	"86":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 86s")),
	"87":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 87s")),
	"88":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 88s")),
	"89":    fmt.Sprintf("%s %s.", B("d8 gold doubloons"), I("worth 89s")),
	"90+":   B(" Random Thing of Importance (pg. 60)."),
}

var thingsOfImportance = map[string]string{
	"01": "animal pelt",
	"02": "oyster pearl",
	"03": "silver locket",
	"04": "conch shell",
	"05": "pipe carved from wood",
	"06": "pipe carved from bone",
	"07": "small jade figurine",
	"08": "ancient gold coin",
	"09": "ruined piece of a treasure map",
	"10": "map of an unknown place",
	"11": "diary written by an ancestor",
	"12": "silver ring",
	"13": "ivory chess piece",
	"14": "sea creature carved from obsidian",
	"15": "spherical prism",
	"16": "jar containing a severed hand",
	"17": "necklace of bones & feathers",
	"18": "book of scripture",
	"19": "novel you loved as a child",
	"20": "bizarre silk handkerchief",
	"21": "pouch containing animal teeth",
	"22": "old fillet knife",
	"23": "fossil of an extinct fish",
	"24": "piece of colorful coral",
	"25": "small ship in a bottle",
	"26": "letter from a loved one",
	"27": "the journal of a dead explorer",
	"28": "stone embossed with a mermaid",
	"29": "vial of holy water from clergy in your hometown",
	"30": "the remains of a small squid in a jar",
	"31": "precious cooking salts in a tiny chest",
	"32": "tankard made from a horn",
	"33": "jar of the finest tobacco",
	"34": "golden letter opener",
	"35": "small, cast bronze owl figurine",
	"36": "collection of sea shells and rocks",
	"37": "necklace carved from jade",
	"38": "a recently deceased relative's will naming you as the sole heir",
	"39": "drawing of a loved one",
	"40": "bag of “magical” white powder",
	"41": "old rusted key with a blue gem that glows in the moonlight",
	"42": "compass that doesn't point north",
	"43": "clay jar you are using as an urn",
	"44": "definitive proof of an enemy's (or loved one's) crime",
	"45": "small golden bell",
	"46": "old bottle of red wine (Bordeaux, incredible vintage)",
	"47": "jar of dried jellyfish dust",
	"48": "multi-colored feather",
	"49": "necklace from a loved one",
	"50": "ring that doesn't fit on your fingers",
	"51": "single diamond earring",
	"52": "finely made leather eye patch",
	"53": "set of gardening tools",
	"54": "dried flower",
	"55": "animal skull",
	"56": "human skull",
	"57": "gem that glows in seawater",
	"58": "dinosaur or monster bone or claw",
	"59": "jar of fireflies",
	"60": "leather-bound tome in a language you don't recognize",
	"61": "blueprints to a new type of ship",
	"62": "carved arrowhead",
	"63": "stone tablet inscribed with ancient pictographs or hieroglyphs",
	"64": "perfect cube made of crystal",
	"65": "tattoo, d4: 1 love, 2 revenge, 3 ancestors, 4 unknown origin",
	"66": "bottle of perfumed oil",
	"67": "broken set of manacles",
	"68": "broken compass",
	"69": "pistol with one shot meant for someone special",
	"70": "flag of personal significance",
	"71": "broken spyglass with a scroll or  map hidden inside",
	"72": "length of rope you made",
	"73": "carved gaming pieces",
	"74": "set of rune stones",
	"75": "twig from a very old tree",
	"76": "noose taken from a corpse",
	"77": "6' length of chain",
	"78": "4d10 scars from lashes on your back",
	"79": "long scar on your face",
	"80": "two coconut shells",
	"81": "dark robe, cape, or cloak",
	"82": "cask of strong sassafras beer",
	"83": "set of keys on a large key ring",
	"84": "small keg of something valuable (rum, powder, ashes, ASH)",
	"85": "magnifying lens (glass only)",
	"86": "cork from a bottle, from a special occasion",
	"87": "cannonball",
	"88": "deck of cards with 1d4 cards missing and 1d6 'extra' cards",
	"89": "garment from someone special",
	"90": "wanted poster, d4: 1 legend, 2 enemy, 3 loved one, 4 stranger",
	"91": "fancy wig",
	"92": "letter of political importance",
	"93": "tanned whale skin or jar of blubber",
	"94": "petrified egg",
	"95": "monkey paw extending 1 finger",
	"96": "memorized poem that sounds  like a map",
	"97": "medallion that might be the top of a staff",
	"98": "talisman shaped like a snake",
	"99": "glass vial of dark blood",
	"00": "shard of crystal",
}

// Endpages, realistically, a GM screen

var meleeWeapons = map[string]any{
	"anchor":            []string{"d10", "60s", "2 handed"},
	"bayonet":           []string{"d4", "15s"},
	"belaying pin":      []string{"d4", "10s"},
	"boarding axe":      []string{"d6", "20s"},
	"boarding pike":     []string{"d10", "60s", "2 handed"},
	"broadsword":        []string{"d8", "35s"},
	"broken bottle":     []string{"d2", "-"},
	"cat o' nine tails": []string{"d4", "15s"},
	"chain":             []string{"d6", "25s"},
	"cudgel":            []string{"d4", "10s"},
	"cutlass":           []string{"d6", "25s"},
	"fine rapier":       []string{"d8", " 50s"},
	"grappling hook":    []string{"d6", "35s"},
	"harpoon":           []string{"d8", "35s"},
	"hatchet":           []string{"d6", "20s"},
	"heavy club":        []string{"d6", "20s"},
	"hook":              []string{"d4", "8s"},
	"knife/dagger":      []string{"d4", "10s"},
	"machete":           []string{"d6", "25s"},
	"marlinspike":       []string{"d4", "10s"},
	"officer’s cutlass": []string{"d8", " 50s"},
	"rapier":            []string{"d6", "30s"},
	"scimitar":          []string{"d6", "25s"},
	"smallsword":        []string{"d4", "20s"},
	"tomahawk":          []string{"d6", "20s"},
	"unarmed/insults":   []string{"d2", "-"},
	"whale bone":        []string{"d4", "-"},
	"wood plank":        []string{"d4", "-"},
}

var rangedWeapons = map[string]any{
	"blowpipe":         []string{"–", "30s", I("See darts")},
	"blunderbuss":      []string{"d4(d10)", "65s", "Reload 2, d10 within 10'"},
	"buccaneer musket": []string{"2d8", "100s", "Reload 2"},
	"flintlock pistol": []string{"2d4", "50s", "Reload 2"},
	"harpoon gun":      []string{"d8", "60s", "Strength DR12 or pulled"},
	"musket":           []string{"2d6", "80s", "Reload 2"},
	"throwing axes":    []string{"d6", "20s "},
	"throwing knives":  []string{"d4", "8s "},
}

var ammo = map[string]any{
	"20 rounds of shot": []string{"-", "10s"},
	"10 berserk darts":  []string{"d4+", "20s", "Toughness DR12 or attack closest creature for d4 rounds"},
	"10 poison darts":   []string{"d4+", "20s", "Toughness DR12 or d6 damage"},
	"10 sleep darts":    []string{"d4+", "20s", "Toughness DR12 or sleep d6 rounds"},
}

var bombs = map[string]any{
	"smoke bomb":      []string{"-", "10s", "Blind for d4 rounds"},
	"improv. grenade": []string{"d10", "20s"},
	"clay grenade":    []string{"2d8", "30s"},
	"iron grenade":    []string{"3d6", "40s"},
	"fire pot":        []string{"d6", "15s", "d6/turn: 1-2 spreads, 6 fire goes out."},
	"stink ball":      []string{"2d4", "20s", "Toughness DR12 or poisoned"},
}

var bombsText = "Test Agility DR12 to hit an area. Hit: Creatures within 5' of the area test Agility DR12 or take damage. Fumble: hit self and/or d4 allies instead. Crit: x2 dmg."

// TODOs:
//	Endpages content
//	The rest of it
