# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o genrpg main.go

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: genrpg-linux
        path: ./genrpg

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o genrpg main.go

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: genrpg-macos
        path: ./genrpg

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o genrpg main.go

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: genrpg-windows
        path: ./genrpg
