package shadowdark

var monsters = map[string]any{
	"name":         "Monster Data",
	"rulesSection": "",
	"description":  "",
	"entries": []map[string]string{
		{
			"name":      "ABOLETH",
			"tags":      "aberration",
			"level":     "8",
			"biome":     "deeps,river/coast,swamp",
			"alignment": "C",
			"move":      "swim",
			"attack":    "",
			"page":      "194",
			"statblock": "AC 16, HP 39, ATK 2 tentacle (near) +5 (1d8 + curse) or 1 tail +5 (3d6), MV near (swim), S +4, D -1, C +3, I +4, W +2, Ch +2, AL C, LV 8",
		},
		{
			"name":      "ACOLYTE",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "ruins,tomb",
			"alignment": "L",
			"move":      "",
			"attack":    "spell",
			"page":      "194",
			"statblock": "AC 12, HP 4, ATK 1 mace +1 (1d6) or 1 spell +2, MV near, S +1, D -1, C+0, I -1, W +2, Ch +0, AL L, LV 1",
		},
		{
			"name":      "ANGEL, DOMINI",
			"tags":      "celestial,angel",
			"level":     "9",
			"biome":     "*",
			"alignment": "L",
			"move":      "fly",
			"attack":    "",
			"page":      "195",
			"statblock": "AC 17 (plate mail + shield), HP 42, ATK 3 bastard sword +7 (1d8) or 1 horn, MV near (fly), S +4, D +1, C+2, I +3, W +4, Ch +4, AL L, LV 9",
		},
		{
			"name":      "ANGEL, PRINCIPI",
			"tags":      "celestial,angel",
			"level":     "11",
			"biome":     "*",
			"alignment": "L",
			"move":      "fly",
			"attack":    "",
			"page":      "195",
			"statblock": "AC 16 (+1 plate mail), HP 53, ATK 3 silvered bastard sword +9 (1d10), MV double near (fly), S +4, D +2, C +4, I +4, W +4, Ch +4, AL L, LV 11",
		},
		{
			"name":      "ANGEL, SERAPH",
			"tags":      "celestial,angel",
			"level":     "3",
			"biome":     "*",
			"alignment": "L",
			"move":      "fly",
			"attack":    "",
			"page":      "195",
			"statblock": "AC 14 (chainmail), HP 14, ATK 2 longsword +3 (1d8), MV near (fly), S +3, D +1, C +1, I +2, W +3, Ch +3, AL L, LV 3",
		},
		{
			"name":      "ANIMATED ARMOR",
			"tags":      "construct",
			"level":     "2",
			"biome":     "ruins,tomb",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "196",
			"statblock": "AC 15, HP 11, ATK 1 longsword +3 (1d8), MV near, S +3, D -1, C +2, I -1, W +1, Ch +0, AL C, LV 2",
		},
		{
			"name":      "ANKHEG",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "cave,deeps,desert,grassland",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "",
			"page":      "196",
			"statblock": "AC 14, HP 14, ATK 1 bite +4 (1d6) or 1 acid spray (near) +4 (2d6), MV near (burrow), S +2, D +2, C+1, I -2, W +1, Ch -2, AL N, LV 3",
		},
		{
			"name":      "APE",
			"tags":      "animal",
			"level":     "2",
			"biome":     "forest,mountain,river/coast,swamp",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "196",
			"statblock": "AC 12, HP 10, ATK 1 fist +2 (1d6) or 1 rock (far) +2 (1d4), MV near (climb), S +2, D +2, C +1, I -2, W +1, Ch +0, AL N, LV 2",
		},
		{
			"name":      "APE, SNOW",
			"tags":      "animal",
			"level":     "4",
			"biome":     "arctic",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "196",
			"statblock": "AC 13, HP 19, ATK 2 fist +4 (1d6) or 1 rock (far) +4 (2d6), MV near (climb), S +3, D +1, C +1, I -2, W +1, Ch +0, AL N, LV 4",
		},
		{
			"name":      "APPRENTICE",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "arctic,cave,desert,forest,grassland,jungle,mountain,river/coast,ruins,swamp,tomb",
			"alignment": "N",
			"move":      "",
			"attack":    "spell",
			"page":      "196",
			"statblock": "AC 11, HP 3, ATK 1 dagger (close/near) +1 (1d4) or 1 spell +2, MV near, S -1, D +1, C -1, I +2, W +0, Ch+0, AL N, LV 1",
		},
		{
			"name":      "ARCHANGEL",
			"tags":      "celestial,angel",
			"level":     "16",
			"biome":     "*",
			"alignment": "L",
			"move":      "fly",
			"attack":    "fire",
			"page":      "195",
			"statblock": "AC 18 (+3 plate mail), HP 76, ATK3 flaming greatsword +10 (2d12), MV double near (fly), S +5, D +2, C+4, I +4, W +5, Ch +5, AL L, LV 16",
		},
		{
			"name":      "ARCHDEVIL",
			"tags":      "fiend,devil",
			"level":     "16",
			"biome":     "*",
			"alignment": "C",
			"move":      "teleport",
			"attack":    "",
			"page":      "206",
			"statblock": "AC 19, HP 76, ATK 4 iron scepter +10 (3d10) or 1 soulbind, MV far (teleport), S +5, D +4, C +4, I +5, W +4, Ch +7, AL C, LV 16",
		},
		{
			"name":      "ARCHMAGE",
			"tags":      "humanoid",
			"level":     "10",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "spell",
			"page":      "197",
			"statblock": "AC 12, HP 44, ATK 2 spell +7, MV near, S -1, D +2, C -1, I +4, W +2, Ch+1, AL L, LV 10",
		},
		{
			"name":      "ASSASSIN",
			"tags":      "humanoid",
			"level":     "8",
			"biome":     "*",
			"alignment": "C",
			"move":      "climb",
			"attack":    "poison",
			"page":      "197",
			"statblock": "AC 15 (leather), HP 38, ATK 2 poisoned dagger (close/near) +6 (2d4), MV near (climb), S +2, D +4, C +2, I +2, W +3, Ch +3, AL C, LV 8",
		},
		{
			"name":      "AZER",
			"tags":      "elemental",
			"level":     "3",
			"biome":     "cave,deeps,mountain",
			"alignment": "L",
			"move":      "",
			"attack":    "fire",
			"page":      "197",
			"statblock": "AC 15, HP 15, ATK 2 flaming warhammer +3 (1d10, ignites flammables) or 1 crossbow (far) +0 (1d6), MV near, S +3, D +0, C+2, I +0, W +0, Ch +0, AL L, LV 3",
		},
		{
			"name":      "BADGER",
			"tags":      "animal",
			"level":     "1",
			"biome":     "forest",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "",
			"page":      "197",
			"statblock": "AC 11, HP 5, ATK 2 claw +2 (1d4), MV near (burrow), S +2, D +0, C+1, I -3, W +1, Ch -2, AL N, LV 1",
		},
		{
			"name":      "BANDIT",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "arctic,desert,mountain,river/coast,ruins,tomb",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "197",
			"statblock": "AC 13 (leather + shield), HP 4, ATK 1 club +1 (1d4) or 1 shortbow (far) +0 (1d4), MV near, S +1, D +0, C +0, I -1, W +0, Ch -1, AL C, LV 1",
		},
		{
			"name":      "BASILISK",
			"tags":      "monstrosity",
			"level":     "5",
			"biome":     "cave,grassland,river/coast,swamp",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "198",
			"statblock": "AC 14, HP 25, ATK 2 bite +4 (2d6 + petrify), MV near, S +3, D +1, C +3, I -3, W +1, Ch -3, AL N, LV 5",
		},
		{
			"name":      "BAT, GIANT",
			"tags":      "animal,giant",
			"level":     "2",
			"biome":     "cave,deeps,mountain,ruins",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "198",
			"statblock": "AC 12, HP 9, ATK 1 bite +2 (1d6), MV near (fly), S -1, D +2, C +0, I -3, W +1, Ch -3, AL N, LV 2",
		},
		{
			"name":      "BAT, SWARM",
			"tags":      "animal,swarm",
			"level":     "4",
			"biome":     "cave,mountain,ruins",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "198",
			"statblock": "AC 12, HP 18, ATK 3 bite +2 (1d6), MV near (fly), S -3, D +2, C +0, I -3, W +1, Ch -3, AL N, LV 4",
		},
		{
			"name":      "BEAR, BROWN",
			"tags":      "animal",
			"level":     "5",
			"biome":     "forest,grassland",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "198",
			"statblock": "AC 13, HP 25, ATK 2 claw +4 (1d8), MV near (climb) S +4, D +1, C +3, I-2, W +1, Ch -2, AL N, LV 5",
		},
		{
			"name":      "BEAR, POLAR",
			"tags":      "animal",
			"level":     "7",
			"biome":     "arctic",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "198",
			"statblock": "AC 13, HP 34, ATK 2 claw +6 (2d6), MV near (climb), S +4, D +1, C +3, I-2, W +1, Ch -2, AL N, LV 7",
		},
		{
			"name":      "BEASTMAN",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "cave,deeps,mountain,ruins",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "198",
			"statblock": "AC 12 (leather), HP 5, ATK 1 spear (close/near) +2 (1d6 + 1), MV near, S +2, D +1, C +1, I -2, W +1, Ch -1, AL C, LV 1",
		},
		{
			"name":      "BERSERKER",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "desert,forest,grassland,jungle",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "199",
			"statblock": "AC 12 (leather), HP 10, ATK 1 greataxe +2 (1d10) or 1 spear (close/near) +2 (1d6), MV near, S+2, D +1, C +1, I +0, W +1, Ch +0, AL N, LV 2",
		},
		{
			"name":      "BLACK PUDDING",
			"tags":      "ooze",
			"level":     "6",
			"biome":     "arctic,cave,deeps,river/coast,ruins",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "199",
			"statblock": "AC 9, HP 30, ATK 3 tentacle +4 (2d6), MV near (climb), S +2, D -1, C +3, I -4, W -3, Ch -4, AL N, LV 6",
		},
		{
			"name":      "BOAR",
			"tags":      "animal",
			"level":     "3",
			"biome":     "forest,grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "199",
			"statblock": "AC 12, HP 14, ATK 2 tusk +3 (1d6), MV near, S +3, D +0, C +1, I -2, W+1, Ch -2, AL N, LV 3",
		},
		{
			"name":      "BRACHIOSAURUS",
			"tags":      "dinosaur",
			"level":     "12",
			"biome":     "forest,jungle",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "208",
			"statblock": "AC 13, HP 57, ATK 3 stomp +7 (2d10), MV double near, S +6, D -1, C +3, I -3, W +1, Ch -3, AL N, LV 12",
		},
		{
			"name":      "BRAIN EATER",
			"tags":      "aberration",
			"level":     "8",
			"biome":     "deeps",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "199",
			"statblock": "AC 14 (leather), HP 36, ATK 4 tentacle +5 (1d8 + latch) or 1 mind blast or 1 mind control, MV near, S +2, D +3, C +0, I +4, W +2, Ch +4, AL C, LV 8",
		},
		{
			"name":      "BUGBEAR",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "cave",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "200",
			"statblock": "AC 13 (leather + shield), HP 14, ATK 2 spiked mace +3 (1d6), MV near, S +3, D +0, C +1, I -1, W +0, Ch -2, AL C, LV 3",
		},
		{
			"name":      "BULETTE",
			"tags":      "monstrosity",
			"level":     "8",
			"biome":     "cave,desert,grassland",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "",
			"page":      "200",
			"statblock": "AC 17, HP 40, ATK 3 bite +5 (2d6) or 1 leap, MV near (burrow), S +5, D +1, C +4, I -3, W +1, Ch -2, AL N, LV 8",
		},
		{
			"name":      "CAMEL",
			"tags":      "animal",
			"level":     "2",
			"biome":     "desert",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "200",
			"statblock": "AC 10, HP 12, ATK 1 hoof +3 (1d6) or 1 spit (near) +0 (1d4), MV double near, S +3, D +0, C +3, I -2, W +1, Ch -3, AL N, LV 2",
		},
		{
			"name":      "CAVE BRUTE",
			"tags":      "insect",
			"level":     "6",
			"biome":     "cave,deeps,ruins",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "",
			"page":      "200",
			"statblock": "AC 14, HP 28, ATK 2 claw +5 (1d8) and 1 mandible +5 (1d10), MV near (burrow), S +4, D +1, C +1, I-3, W +1, Ch -3, AL N, LV 6",
		},
		{
			"name":      "CAVE CREEPER",
			"tags":      "insect",
			"level":     "4",
			"biome":     "cave,deeps,ruins,tomb",
			"alignment": "N",
			"move":      "climb",
			"attack":    "toxin",
			"page":      "200",
			"statblock": "AC 12, HP 18, ATK 1 bite +3 (1d6) and 1 tentacles +3 (1d8 + toxin), MV near (climb), S +2, D +2, C +0, I -3, W +1, Ch -3, AL N, LV 4",
		},
		{
			"name":      "CENTAUR",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "desert,forest,grassland,river/coast",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "201",
			"statblock": "AC 12 (leather), HP 14, ATK 2 spear (close/near) +2 (1d6) or 1 longbow (far) +1 (1d8), MV double near, S +2, D +1, C +1, I +0, W +2, Ch +1, AL N, LV 3",
		},
		{
			"name":      "CENTIPEDE, GIANT",
			"tags":      "insect,giant",
			"level":     "1",
			"biome":     "cave,forest,jungle",
			"alignment": "N",
			"move":      "climb",
			"attack":    "poison",
			"page":      "201",
			"statblock": "AC 11, HP 4, ATK 1 bite +1 (1d4 + poison), MV near (climb), S -3, D+1, C +0, I -4, W -3, Ch -4, AL N, LV 1",
		},
		{
			"name":      "CENTIPEDE, SWARM",
			"tags":      "insect,swarm",
			"level":     "4",
			"biome":     "cave,forest,jungle,tomb",
			"alignment": "N",
			"move":      "climb",
			"attack":    "poison",
			"page":      "201",
			"statblock": "AC 11, HP 18, ATK 3 bite +1 (1d4 + poison), MV near (climb), S -3, D+1, C +0, I -4, W -3, Ch -4, AL N, LV 4",
		},
		{
			"name":      "CHIMERA",
			"tags":      "monstrosity",
			"level":     "10",
			"biome":     "cave,grassland",
			"alignment": "C",
			"move":      "fly",
			"attack":    "fire",
			"page":      "201",
			"statblock": "AC 16, HP 49, ATK 4 rend +7 (2d8) and 1 fire breath, MV double near (fly), S +5, D +4, C +4, I -3, W+2, Ch -1, AL C, LV 10",
		},
		{
			"name":      "CHUUL",
			"tags":      "insect",
			"level":     "5",
			"biome":     "ocean,river/coast",
			"alignment": "C",
			"move":      "swim",
			"attack":    "",
			"page":      "201",
			"statblock": "AC 15, HP 25, ATK 2 pincer +4 (1d8 + grab), MV near (swim), S+3, D -1, C +3, I -1, W +1, Ch -2, AL C, LV 5",
		},
		{
			"name":      "CLOAKER",
			"tags":      "aberration",
			"level":     "6",
			"biome":     "cave,deeps",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "202",
			"statblock": "AC 13, HP 28, ATK 3 lash +4 (1d8) or 1 screech, MV near (fly), S +2, D +3, C +1, I +1, W +1, Ch +0, AL C, LV 6",
		},
		{
			"name":      "COCKATRICE",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "cave,deeps,desert,swamp",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "202",
			"statblock": "AC 11, HP 14, ATK 1 bite +1 (1d4 + petrify), MV near (fly), S -2, D +1, C+1, I -3, W +1, Ch -3, AL N, LV 3",
		},
		{
			"name":      "COUATL",
			"tags":      "celestial",
			"level":     "9",
			"biome":     "jungle",
			"alignment": "L",
			"move":      "fly",
			"attack":    "poison",
			"page":      "202",
			"statblock": "AC 16, HP 42, ATK 3 bite +6 (2d6 + poison), MV near (fly), S +2, D +3, C +2, I +4, W +4, Ch +5, AL L, LV 9",
		},
		{
			"name":      "CRAB, GIANT",
			"tags":      "animal,giant",
			"level":     "5",
			"biome":     "ocean,river/coast",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "202",
			"statblock": "AC 15, HP 24, ATK 2 pincer +4 (1d8 + crush), MV near (swim), S+3, D +0, C +2, I -3, W +0, Ch -3, AL N, LV 5",
		},
		{
			"name":      "CROCODILE",
			"tags":      "animal",
			"level":     "4",
			"biome":     "jungle,swamp",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "203",
			"statblock": "AC 14, HP 20, ATK 2 bite +3 (1d8), MV near (swim), S +3, D +1, C +2, I-2, W +1, Ch -2, AL N, LV 4",
		},
		{
			"name":      "CULTIST",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "spell",
			"page":      "203",
			"statblock": "AC 14 (chainmail + shield), HP9, ATK 1 longsword +1 (1d8) or 1 spell +2, MV near, S +1, D -1, C +0, I-1, W +2, Ch +0, AL C, LV 2",
		},
		{
			"name":      "CYCLOPS",
			"tags":      "humanoid,giant",
			"level":     "8",
			"biome":     "forest,grassland,jungle,mountain",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "203",
			"statblock": "AC 11 (leather), HP 38, ATK 2 greatclub +7 (2d8) or 1 rock (far) +5 (1d12), MV double near, S +5, D +0, C +2, I -1, W -2, Ch +0, AL C, LV 8",
		},
		{
			"name":      "DARKMANTLE",
			"tags":      "aberration",
			"level":     "1",
			"biome":     "cave,deeps,ruins",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "203",
			"statblock": "AC 13, HP 4 ATK 1 bite +3 (1d4) or 1 darkness, MV near (fly), S -2, D+3, C +0, I -3, W +0, Ch -3, AL N, LV 1",
		},
		{
			"name":      "DEEP ONE",
			"tags":      "aberration",
			"level":     "2",
			"biome":     "deeps,ocean,river/coast",
			"alignment": "C",
			"move":      "swim",
			"attack":    "",
			"page":      "203",
			"statblock": "AC 13, HP 10, ATK 2 spear (close/near) +2 (1d6), MV near (swim), S+2, D +1, C +1, I -2, W +0, Ch -2, AL C, LV 2",
		},
		{
			"name":      "DEMON, BALOR",
			"tags":      "fiend,demon",
			"level":     "16",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "fire",
			"page":      "204",
			"statblock": "AC 19, HP 77, ATK 3 greatsword +10 (2d12 + hellfire) and 1 fire whip (near) +10 (2d6 + grab), MV double near (fly), S +6, D +2, C +5, I +4, W +3, Ch +4, AL C, LV 16",
		},
		{
			"name":      "DEMON, DRETCH",
			"tags":      "fiend,demon",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "204",
			"statblock": "AC 12, HP 11, ATK 1 claw +2 (1d6) or 1 gas, MV near, S +2, D +0, C +2, I -2, W -1, Ch -3, AL C, LV 2",
		},
		{
			"name":      "DEMON, GLABREZU",
			"tags":      "fiend,demon",
			"level":     "8",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "204",
			"statblock": "AC 15, HP 40, ATK 2 pincer +7 (2d8 + crush), MV near, S +4, D +1, C +4, I +3, W +2, Ch +2, AL C, LV 8",
		},
		{
			"name":      "DEMON, MARILITH",
			"tags":      "fiend,demon",
			"level":     "9",
			"biome":     "*",
			"alignment": "C",
			"move":      "climb",
			"attack":    "",
			"page":      "205",
			"statblock": "AC 17 (plate mail), HP 43, ATK6 longsword +7 (1d8), MV near (climb), S +5, D +4, C +3, I +3, W+3, Ch +4, AL C, LV 9",
		},
		{
			"name":      "DEMON, VROCK",
			"tags":      "fiend,demon",
			"level":     "5",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "205",
			"statblock": "AC 14, HP 24, ATK 2 talons +4 (1d8) or 1 screech, MV near (fly), S+2, D +2, C +2, I -1, W +1, Ch +0, AL C, LV 5",
		},
		{
			"name":      "DEVIL, BARBED",
			"tags":      "fiend,devil",
			"level":     "3",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "fire",
			"page":      "206",
			"statblock": "AC 13, HP 14, ATK 2 spine (near) +3 (1d6 + barb) or 1 fire blast (far) +3 (1d8), MV near, S +2, D +3, C +1, I +1, W +1, Ch +1, AL C, LV 3",
		},
		{
			"name":      "DEVIL, CUBI",
			"tags":      "fiend,devil",
			"level":     "6",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "207",
			"statblock": "AC 14, HP 29, ATK 1 kiss +4 (1d6 + drain) or 1 charm, MV near (fly), S +2, D +4, C +2, I +3, W +2, Ch +5, AL C, LV 6",
		},
		{
			"name":      "DEVIL, ERINYES",
			"tags":      "fiend,devil",
			"level":     "9",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "poison",
			"page":      "207",
			"statblock": "AC 17 (+1 plate mail), HP 43, ATK 3 greatsword +8 (1d12) or 2 longbow (far) +8 (1d8 + poison), MV double near (fly), S +4, D +4, C +3, I +4, W +4, Ch +5, AL C, LV 9",
		},
		{
			"name":      "DEVIL, HORNED",
			"tags":      "fiend,devil",
			"level":     "7",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "fire",
			"page":      "207",
			"statblock": "AC 16, HP 35, ATK 2 burning trident (near) +7 (2d6) or 1 fire blast (far) +4 (2d8), MV double near (fly), S +5, D +2, C +4, I +2, W+1, Ch +2, AL C, LV 7",
		},
		{
			"name":      "DEVIL, IMP",
			"tags":      "fiend,devil",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "poison",
			"page":      "207",
			"statblock": "AC 13, HP 9, ATK 1 stinger +3 (1d4 + poison), MV near (fly), S -2, D +3, C +0, I +1, W +0, Ch +2, AL C, LV 2",
		},
		{
			"name":      "DJINNI",
			"tags":      "elemental",
			"level":     "10",
			"biome":     "desert",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "209",
			"statblock": "AC 14, HP 48, ATK 3 scimitar +7 (1d12) or 1 whirlwind, MV double near (fly), S +4, D +4, C +3, I +4, W+3, Ch +3, AL N, LV 10",
		},
		{
			"name":      "DOPPELGANGER",
			"tags":      "monstrosity",
			"level":     "4",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "209",
			"statblock": "AC 12, HP 20, ATK 1 dagger (close/near) +2 (1d4), MV near, S+1, D +2, C +2, I +1, W +0, Ch +4, AL C, LV 4",
		},
		{
			"name":      "DRAGON, DESERT",
			"tags":      "dragon",
			"level":     "13",
			"biome":     "desert",
			"alignment": "L",
			"move":      "fly",
			"attack":    "electric",
			"page":      "210",
			"statblock": "AC 17, HP 61, ATK 3 rend +9 (2d10) or 1 lightning breath, MV double near (fly), S +5, D +3, C +3, I +4, W+5, Ch +5, AL L, LV 13",
		},
		{
			"name":      "DRAGON, FIRE",
			"tags":      "dragon",
			"level":     "17",
			"biome":     "cave,desert,mountain",
			"alignment": "C",
			"move":      "fly",
			"attack":    "fire",
			"page":      "210",
			"statblock": "AC 18, HP 80, ATK 4 rend +11 (2d12) or 1 fire breath, MV double near (fly), S +6, D +5, C +4, I +4, W+4, Ch +5, AL C, LV 17",
		},
		{
			"name":      "DRAGON, FOREST",
			"tags":      "dragon",
			"level":     "12",
			"biome":     "forest,jungle",
			"alignment": "N",
			"move":      "fly",
			"attack":    "poison",
			"page":      "211",
			"statblock": "AC 16, HP 58, ATK 3 rend +8 (2d8) or 1 poison breath, MV double near (fly), S +4, D +3, C +4, I +3, W+3, Ch +4, AL N, LV 12",
		},
		{
			"name":      "DRAGON, FROST",
			"tags":      "dragon",
			"level":     "14",
			"biome":     "arctic",
			"alignment": "N",
			"move":      "fly",
			"attack":    "ice",
			"page":      "211",
			"statblock": "AC 17, HP 68, ATK 4 rend +9 (2d10) or 1 ice breath, MV double near (fly), S +4, D +3, C +5, I +3, W+4, Ch +3, AL N, LV 14",
		},
		{
			"name":      "DRAGON, SEA",
			"tags":      "dragon",
			"level":     "16",
			"biome":     "ocean,river/coast",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "211",
			"statblock": "AC 17, HP 76, ATK 4 rend +10 (2d10) or 1 steam breath or 1 water spout, MV double near (fly, swim), S +5, D +6, C +4, I +4, W+5, Ch +5, AL L, LV 16",
		},
		{
			"name":      "DRAGON, SWAMP",
			"tags":      "dragon",
			"level":     "12",
			"biome":     "swamp,river/coast",
			"alignment": "C",
			"move":      "burrow",
			"attack":    "",
			"page":      "211",
			"statblock": "AC 16, HP 58, ATK 3 rend +8 (2d10) or 1 smog breath, MV double near (burrow, swim), S +5, D +3, C +4, I +4, W +3, Ch +3, AL C, LV 12",
		},
		{
			"name":      "DROW",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "cave,deeps,jungle",
			"alignment": "C",
			"move":      "",
			"attack":    "poison",
			"page":      "212",
			"statblock": "AC 16 (mithral chainmail), HP 9, ATK 1 poison dart (near) +3 (1d4 + poison) or 1 longsword +1 (1d8), MV near, S +0, D +3, C +0, I +1, W+1, Ch +1, AL C, LV 2",
		},
		{
			"name":      "DROW, DRIDER",
			"tags":      "monstrosity",
			"level":     "6",
			"biome":     "cave,deeps,jungle",
			"alignment": "C",
			"move":      "climb",
			"attack":    "poison",
			"page":      "212",
			"statblock": "AC 16 (mithral chainmail), HP 29, ATK 3 longsword +3 (1d8) or 2 longbow (far) +3 (1d8 + poison), MV near (climb), S +3, D +3, C +2, I +2, W +2, Ch +0, AL C, LV 6",
		},
		{
			"name":      "DROW, PRIESTESS",
			"tags":      "humanoid",
			"level":     "6",
			"biome":     "cave,deeps,jungle",
			"alignment": "C",
			"move":      "",
			"attack":    "spell,poison",
			"page":      "212",
			"statblock": "AC 16 (mithral chainmail), HP 28, ATK 3 snake whip (near) +4 (1d8 + poison) or 1 spell +4, MV near, S +2, D +3, C +1, I +3, W +4, Ch +3, AL C, LV 6",
		},
		{
			"name":      "DRUID",
			"tags":      "humanoid",
			"level":     "7",
			"biome":     "forest,grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "spell",
			"page":      "213",
			"statblock": "AC 11, HP 31, ATK 1 staff +0 (1d4) or 2 spell +5, MV near, S +0, D +1, C +0, I +4, W +3, Ch +0, AL N, LV 7",
		},
		{
			"name":      "DRYAD",
			"tags":      "fey",
			"level":     "4",
			"biome":     "forest,jungle",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "213",
			"statblock": "AC 13, HP 19, ATK 1 staff -1 (1d4) or 1 charm, MV near, S -1, D +2, C +1, I +1, W +3, Ch +4, AL N, LV 4",
		},
		{
			"name":      "DUERGAR",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "cave,deeps",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "213",
			"statblock": "AC 15 (chainmail + shield), HP 12, ATK 1 war pick +2 (1d6), MV near, S +2, D +0, C +3, I +0, W -1, Ch -1, AL C, LV 2",
		},
		{
			"name":      "DUNG BEETLE, GIANT",
			"tags":      "insect,giant",
			"level":     "2",
			"biome":     "cave,grassland,ruins",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "214",
			"statblock": "AC 13, HP 10, ATK 1 horn +1 (1d4 + knock), MV near, S +1, D -1, C +1, I-3, W -1, Ch -3, AL N, LV 2",
		},
		{
			"name":      "EFREETI",
			"tags":      "elemental",
			"level":     "9",
			"biome":     "desert",
			"alignment": "C",
			"move":      "fly",
			"attack":    "fire",
			"page":      "214",
			"statblock": "AC 15, HP 43, ATK 3 scimitar +8 (2d10) or 2 fire bolt (far) +5 (2d6), MV near (fly), S +5, D +2, C +3, I +3, W +2, Ch +3, AL C, LV 9",
		},
		{
			"name":      "ELEMENTAL, AIR",
			"tags":      "elemental",
			"level":     "6",
			"biome":     "*",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "215",
			"statblock": "AC 16, HP 29/42, ATK 3 slam +7 (2d6/3d6) or 1 whirlwind, MV double near (fly), S +3, D +5, C +2, I -2, W +1, Ch -2, AL N, LV 6",
		},
		{
			"name":      "ELEMENTAL, EARTH",
			"tags":      "elemental",
			"level":     "6",
			"biome":     "*",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "",
			"page":      "215",
			"statblock": "AC 17, HP 31/44, ATK 3 slam +7 (2d8/3d8) or 1 avalanche, MV near (burrow), S +5, D +0, C +4, I-2, W +1, Ch -2, AL N, LV 6",
		},
		{
			"name":      "ELEMENTAL, FIRE",
			"tags":      "elemental",
			"level":     "6",
			"biome":     "*",
			"alignment": "N",
			"move":      "fly",
			"attack":    "fire",
			"page":      "215",
			"statblock": "AC 15, HP 30/43, ATK 3 slam +6 (2d10/3d10) or 1 inferno, MV near (fly), S +4, D +3, C +3, I -2, W +1, Ch-2, AL N, LV 6",
		},
		{
			"name":      "ELEMENTAL, WATER",
			"tags":      "elemental",
			"level":     "6",
			"biome":     "*",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "215",
			"statblock": "AC 15, HP 29/42, ATK 3 slam +6 (2d6/3d6) or 1 whirlpool, MV double near (swim), S +4, D +2, C+2, I -2, W +1, Ch -2, AL N, LV 6",
		},
		{
			"name":      "ELEPHANT",
			"tags":      "animal",
			"level":     "7",
			"biome":     "grassland,jungle,river/coast",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "216",
			"statblock": "AC 14, HP 34, ATK 2 tusks +6 (1d8), MV near, S +5, D +0, C +3, I-2, W +1, Ch +0, AL N, LV 7",
		},
		{
			"name":      "ELF",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "216",
			"statblock": "AC 13, HP 9, ATK 1 longbow (far) +3 (1d8) or 1 longsword +1 (1d8), MV near, S +0, D +3, C +0, I +1, W+1, Ch +1, AL L, LV 2",
		},
		{
			"name":      "ETTERCAP",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "cave,mountain",
			"alignment": "C",
			"move":      "climb",
			"attack":    "poison",
			"page":      "216",
			"statblock": "AC 12, HP 14, ATK 2 bite +2 (1d6) or 1 poison web (near) +2, MV near (climb), S +0, D +2, C +1, I +0, W +0, Ch -1, AL C, LV 3",
		},
		{
			"name":      "FAIRY",
			"tags":      "fey",
			"level":     "1",
			"biome":     "forest,jungle",
			"alignment": "N",
			"move":      "fly",
			"attack":    "poison",
			"page":      "216",
			"statblock": "AC 13, HP 4, ATK 1 needle +3 (1 + poison), MV near (fly), S -2, D +3, C +0, I +1, W +0, Ch +1, AL N, LV 1",
		},
		{
			"name":      "FROG, GIANT",
			"tags":      "animal,giant",
			"level":     "2",
			"biome":     "cave,forest,jungle,river/coast,swamp",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "216",
			"statblock": "AC 12, HP 10, ATK 1 tongue and 1 bite +2 (1d6), MV near (swim), S+2, D +2, C +1, I -3, W +0, Ch -3, AL N, LV 2",
		},
		{
			"name":      "GARGOYLE",
			"tags":      "elemental",
			"level":     "4",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "216",
			"statblock": "AC 16, HP 20, ATK 2 claw +3 (1d6), MV near (fly), S +3, D +1, C +2, I +0, W +1, Ch -1, AL C, LV 4",
		},
		{
			"name":      "GELATINOUS CUBE",
			"tags":      "ooze",
			"level":     "5",
			"biome":     "ruins,tomb",
			"alignment": "N",
			"move":      "",
			"attack":    "toxin",
			"page":      "217",
			"statblock": "AC 11, HP 24, ATK 1 touch +4 (1d8 + toxin + engulf), MV near, S +3, D +1, C +2, I -4, W +1, Ch -4, AL N, LV 5",
		},
		{
			"name":      "GHAST",
			"tags":      "undead",
			"level":     "4",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "217",
			"statblock": "AC 11, HP 20, ATK 2 claw +4 (1d8 + paralyze), MV near, S +3, D +1, C+2, I +0, W +0, Ch +2, AL C, LV 4",
		},
		{
			"name":      "GHOST",
			"tags":      "undead",
			"level":     "6",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "life drain",
			"page":      "217",
			"statblock": "AC 13, HP 27, ATK 2 death touch +5 (1d8 + life drain) or 1 possess, MV near (fly), S -2, D +3, C +0, I +0, W +0, Ch +4, AL C, LV 6",
		},
		{
			"name":      "GHOUL",
			"tags":      "undead",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "217",
			"statblock": "AC 11, HP 11, ATK 1 claw +2 (1d6 + paralyze), MV near, S +2, D +1, C+2, I -3, W -1, Ch +0, AL C, LV 2",
		},
		{
			"name":      "GIANT, CLOUD",
			"tags":      "giant",
			"level":     "10",
			"biome":     "arctic,mountain",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "218",
			"statblock": "AC 15 (leather), HP 48, ATK3 morningstar +9 (2d10), MV double near, S +5, D +4, C +3, I +3, W +3, Ch +3, AL N, LV 10",
		},
		{
			"name":      "GIANT, FIRE",
			"tags":      "giant",
			"level":     "9",
			"biome":     "mountain",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "218",
			"statblock": "AC 15 (plate mail), HP 44, ATK 3 greatsword +9 (2d12), MV double near, S +6, D +0, C +4, I +1, W +2, Ch +1, AL C, LV 9",
		},
		{
			"name":      "GIANT, FROST",
			"tags":      "giant",
			"level":     "9",
			"biome":     "arctic,mountain",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "219",
			"statblock": "AC 14 (chainmail), HP 44, ATK 3 greataxe +8 (2d10), MV double near, S +5, D +1, C +4, I +2, W +3, Ch +2, AL C, LV 9",
		},
		{
			"name":      "GIANT, GOAT",
			"tags":      "giant",
			"level":     "8",
			"biome":     "mountain",
			"alignment": "C",
			"move":      "climb",
			"attack":    "",
			"page":      "219",
			"statblock": "AC 12 (leather), HP 39, ATK 2 greatclub +7 (2d8) or 1 boulder (far) +7 (2d10), MV double near (climb), S +4, D +1, C +3, I -2, W+0, Ch -2, AL C, LV 8",
		},
		{
			"name":      "GIANT, HILL",
			"tags":      "giant",
			"level":     "7",
			"biome":     "grassland,mountain",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "219",
			"statblock": "AC 11 (leather), HP 34, ATK 2 greatclub +6 (2d8) or 1 boulder (far) +6 (2d10), MV double near, S+4, D +0, C +3, I -2, W -2, Ch -2, AL C, LV 7",
		},
		{
			"name":      "GIANT, STONE",
			"tags":      "giant",
			"level":     "8",
			"biome":     "mountain",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "219",
			"statblock": "AC 17, HP 40, ATK 2 greatclub +7 (2d8) or 1 boulder (far) +7 (2d10), MV double near, S +4, D +2, C +4, I +1, W +1, Ch -1, AL N, LV 8",
		},
		{
			"name":      "GIANT, STORM",
			"tags":      "giant",
			"level":     "12",
			"biome":     "mountain,ocean",
			"alignment": "L",
			"move":      "swim",
			"attack":    "electric",
			"page":      "219",
			"statblock": "AC 15 (mithral chainmail), HP 58, ATK 3 greatsword +10 (2d12) or 1 lightning bolt, MV double near (swim), S +6, D +2, C +4, I +3, W+4, Ch +4, AL L, LV 12",
		},
		{
			"name":      "GIBBERING MOUTHER",
			"tags":      "aberration",
			"level":     "4",
			"biome":     "deeps",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "220",
			"statblock": "AC 8, HP 21, ATK 2 bite +3 (1d8 + latch), MV near (climb, swim), S+2, D -2, C +3, I -3, W +0, Ch -3, AL N, LV 4",
		},
		{
			"name":      "GLADIATOR",
			"tags":      "humanoid",
			"level":     "3",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "220",
			"statblock": "AC 16 (chainmail + shield), HP15, ATK 2 longsword +3 (1d8) or 1 spear (close/near) +3 (1d6), MV near, S +2, D +1, C +2, I +0, W +0, Ch +1, AL N, LV 3",
		},
		{
			"name":      "GNOLL",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "cave,grassland,swamp",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "220",
			"statblock": "AC 12 (leather), HP 10, ATK 1 spear (close/near) +1 (1d6) or 1 longbow (far) +1 (1d8), MV near, S+1, D +1, C +1, I -1, W +0, Ch -1, AL C, LV 2",
		},
		{
			"name":      "GNOME, DEEP",
			"tags":      "humanoid",
			"level":     "3",
			"biome":     "cave,deeps,ruins",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "220",
			"statblock": "AC 14 (leather + shield), HP 14, ATK 1 pick +3 (1d6) or 1 dart (near) +2 (1d4), MV near, S +2, D +1, C +1, I +1, W +1, Ch +1, AL L, LV 3",
		},
		{
			"name":      "GOBLIN",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "221",
			"statblock": "AC 11, HP 5, ATK 1 club +0 (1d4) or 1 shortbow (far) +1 (1d4), MV near, S +0, D +1, C +1, I -1, W -1, Ch -2, AL C, LV 1",
		},
		{
			"name":      "GOBLIN, BOSS",
			"tags":      "humanoid",
			"level":     "4",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "221",
			"statblock": "AC 14 (chainmail), HP 20, ATK 1 spear (close/near) +3 (1d6), MV near, S +2, D +1, C +2, I -1, W +0, Ch +1, AL C, LV 4",
		},
		{
			"name":      "GOBLIN, SHAMAN",
			"tags":      "humanoid",
			"level":     "4",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "spell",
			"page":      "221",
			"statblock": "AC 12 (leather), HP 19, ATK 1 staff +0 (1d4) or 1 spell +3, MV near, S+0, D +1, C +1, I +0, W +2, Ch +1, AL C, LV 4",
		},
		{
			"name":      "GOLEM, CLAY",
			"tags":      "golem,construct",
			"level":     "8",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "222",
			"statblock": "AC 14, HP 40, ATK 3 slam +6 (1d8), MV near, S +4, D +0, C +4, I-2, W +0, Ch -2, AL N, LV 8",
		},
		{
			"name":      "GOLEM, FLESH",
			"tags":      "golem,construct",
			"level":     "7",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "222",
			"statblock": "AC 9, HP 35, ATK 3 slam +6 (1d8), MV near, S +4, D -1, C +4, I -1, W+1, Ch -3, AL N, LV 7",
		},
		{
			"name":      "GOLEM, IRON",
			"tags":      "golem,construct",
			"level":     "10",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "poison",
			"page":      "222",
			"statblock": "AC 19, HP 49, ATK 3 slam +8 (2d8) or 1 poison breath, MV near, S +5, D -1, C +4, I -2, W +0, Ch -2, AL N, LV 10",
		},
		{
			"name":      "GOLEM, STONE",
			"tags":      "golem,construct",
			"level":     "8",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "222",
			"statblock": "AC 18, HP 40, ATK 3 slam +6 (1d10) and 1 slow, MV near, S +4, D -1, C +4, I -2, W +0, Ch -2, AL N, LV 8",
		},
		{
			"name":      "GORGON",
			"tags":      "monstrosity",
			"level":     "7",
			"biome":     "ruins,tomb",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "223",
			"statblock": "AC 18, HP 33, ATK 2 gore +6 (2d8) or 1 charge or 1 petrifying breath, MV double near, S +4, D +0, C +2, I -3, W +1, Ch -3, AL C, LV 7",
		},
		{
			"name":      "GORILLA",
			"tags":      "animal",
			"level":     "4",
			"biome":     "forest,jungle",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "223",
			"statblock": "AC 12, HP 20, ATK 2 rend +5 (2d6), MV near (climb), S +4, D +2, C +2, I -1, W +1, Ch -1, AL N, LV 4",
		},
		{
			"name":      "GRAY OOZE",
			"tags":      "ooze",
			"level":     "2",
			"biome":     "cave,ruins,swamp,tomb",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "223",
			"statblock": "AC 11, HP 9, ATK 1 tentacle +2 (1d6), MV near (climb), S +1, D +1, C +0, I -4, W -3, Ch -4, AL N, LV 2",
		},
		{
			"name":      "GRICK",
			"tags":      "monstrosity",
			"level":     "4",
			"biome":     "cave,ruins,swamp",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "223",
			"statblock": "AC 14, HP 19, ATK 1 beak +3 (1d8) and 1 tentacle +3 (1d6 + grab), MV near (climb), S +3, D +2, C +1, I -3, W +1, Ch -3, AL N, LV 4",
		},
		{
			"name":      "GRIFFON",
			"tags":      "monstrosity",
			"level":     "4",
			"biome":     "grassland,river/coast",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "224",
			"statblock": "AC 12, HP 19, ATK 2 rend +4 (1d10), MV double near (fly), S +4, D +2, C +1, I -3, W +1, Ch -1, AL N, LV 4",
		},
		{
			"name":      "GRIMLOW",
			"tags":      "monstrosity",
			"level":     "9",
			"biome":     "cave,forest,mountain",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "224",
			"statblock": "AC 12, HP 43, ATK 1 grab and 3 bite +6 (2d8), MV near, S +4, D +2, C +3, I -3, W +1, Ch -2, AL N, LV 9",
		},
		{
			"name":      "GUARD",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "224",
			"statblock": "AC 15 (chainmail + shield), HP 4, ATK 1 spear (close/near) +1 (1d6) or 1 longsword +1 (1d8), MV near, S +1, D +0, C +0, I +0, W +1, Ch +0, AL L, LV 1",
		},
		{
			"name":      "HAG, NIGHT",
			"tags":      "fey",
			"level":     "8",
			"biome":     "deeps,forest,swamp",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "225",
			"statblock": "AC 14, HP 37, ATK 2 bite +6 (1d10) and 1 blind, MV near, S +4, D +2, C +1, I +2, W +3, Ch +3, AL C, LV 8",
		},
		{
			"name":      "HAG, SEA",
			"tags":      "fey",
			"level":     "6",
			"biome":     "ocean,river/coast",
			"alignment": "C",
			"move":      "swim",
			"attack":    "",
			"page":      "225",
			"statblock": "AC 15, HP 28, ATK 2 claw +4 (1d8), MV near (swim), S +2, D +3, C +1, I+1, W +2, Ch +2, AL C, LV 6",
		},
		{
			"name":      "HAG, WEALD",
			"tags":      "fey",
			"level":     "6",
			"biome":     "forest,jungle",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "225",
			"statblock": "AC 14, HP 28, ATK 2 claw +4 (1d8) or 1 drink pain, MV near, S +3, D+2, C +1, I +1, W +2, Ch +3, AL C, LV 6",
		},
		{
			"name":      "HARPY",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "arctic,forest,mountain",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "226",
			"statblock": "AC 13, HP 14, ATK 2 claw +3 (1d6) or 1 song, MV near (fly), S +1, D +3, C +1, I +0, W +0, Ch +1, AL C, LV 3",
		},
		{
			"name":      "HELL HOUND",
			"tags":      "fiend",
			"level":     "4",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "fire",
			"page":      "226",
			"statblock": "AC 13, HP 19, ATK 2 bite +4 (1d8) or 1 fire breath, MV double near, S +2, D +1, C +1, I -2, W +1, Ch -3, AL C, LV 4",
		},
		{
			"name":      "HIPPOGRIFF",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "forest,grassland,river/coast",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "226",
			"statblock": "AC 13, HP 14, ATK 2 rend +3 (1d8), MV double near (fly), S +3, D +3, C+1, I -3, W +1, Ch -2, AL N, LV 3",
		},
		{
			"name":      "HIPPOPOTAMUS",
			"tags":      "animal",
			"level":     "5",
			"biome":     "river/coast,swamp",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "226",
			"statblock": "AC 12, HP 24, ATK 2 bite +4 (1d10), MV near (swim), S +4, D +0, C +2, I -3, W +0, Ch -3, AL N, LV 5",
		},
		{
			"name":      "HOBGOBLIN",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "227",
			"statblock": "AC 15 (chainmail + shield), HP10, ATK 1 longsword +3 (1d8) or 1 longbow (far) +0 (1d8), MV near, S +3, D +0, C +1, I +2, W +1, Ch +1, AL C, LV 2",
		},
		{
			"name":      "HORSE",
			"tags":      "animal",
			"level":     "2",
			"biome":     "forest,grassland,river/coast",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "227",
			"statblock": "AC 11, HP 11, ATK 1 hooves +3 (1d6), MV double near, S +3, D +1, C +2, I -3, W +1, Ch -2, AL N, LV 2",
		},
		{
			"name":      "HYDRA",
			"tags":      "monstrosity",
			"level":     "*",
			"biome":     "deeps,ocean,river/coast,swamp",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "227",
			"statblock": "AC 15, HP *, ATK 1 bite (near) +6 (1d8), MV near (swim), S +5, D +1, C +2, I -2, W +1, Ch -2, AL N, LV *",
		},
		{
			"name":      "INVISIBLE STALKER",
			"tags":      "elemental",
			"level":     "6",
			"biome":     "*",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "227",
			"statblock": "AC 13, HP 29, ATK 3 pummel +4 (1d6), MV near (fly), S +2, D +3, C+2, I +2, W +1, Ch +0, AL N, LV 6",
		},
		{
			"name":      "JELLYFISH",
			"tags":      "animal",
			"level":     "0",
			"biome":     "ocean",
			"alignment": "N",
			"move":      "swim",
			"attack":    "toxin",
			"page":      "228",
			"statblock": "AC 11, HP 1, ATK 1 sting +1 (1 + toxin), MV close (swim), S -4, D+1, C +0, I -4, W +1, Ch -4, AL N, LV 0",
		},
		{
			"name":      "KNIGHT",
			"tags":      "humanoid",
			"level":     "3",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "228",
			"statblock": "AC 17 (plate mail + shield), HP 14, ATK 2 bastard sword +3 (1d8), MV near, S +3, D +0, C +1, I +0, W +0, Ch +1, AL L, LV 3",
		},
		{
			"name":      "KOBOLD",
			"tags":      "humanoid",
			"level":     "0",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "228",
			"statblock": "AC 13 (leather), HP 1, ATK 1 spear (close/near) +0 (1d6), MV near, S-2, D +2, C +0, I -1, W +0, Ch -1, AL C, LV 0",
		},
		{
			"name":      "KOBOLD, SORCERER",
			"tags":      "humanoid",
			"level":     "3",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "spell",
			"page":      "228",
			"statblock": "AC 13 (leather), HP 13, ATK 1 club +1 (1d4) or 1 spell +2, MV near, S-2, D +2, C +0, I -1, W +1, Ch +2, AL C, LV 3",
		},
		{
			"name":      "KRAKEN",
			"tags":      "monstrosity,giant",
			"level":     "17",
			"biome":     "ocean",
			"alignment": "C",
			"move":      "swim",
			"attack":    "electric",
			"page":      "229",
			"statblock": "AC 18, HP 80, ATK 4 tentacle (near) +9 (2d12) or 1 storm or 1d4 lightning bolt, MV double near (swim), S +6, D +3, C +4, I +4, W+3, Ch +4, AL C, LV 17",
		},
		{
			"name":      "LEECH, GIANT",
			"tags":      "animal,giant",
			"level":     "2",
			"biome":     "deeps,river/coast,swamp",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "229",
			"statblock": "AC 9, HP 10, ATK 1 bite +1 (1d4 + attach), MV near (swim), S +1, D -1, C +1, I -3, W -1, Ch -3, AL N, LV 2",
		},
		{
			"name":      "LEPRECHAUN",
			"tags":      "fey",
			"level":     "4",
			"biome":     "forest",
			"alignment": "N",
			"move":      "",
			"attack":    "spell",
			"page":      "230",
			"statblock": "AC 13, HP 19, ATK 1 spell +4, MV near, S +1, D +3, C +1, I +2, W +1, Ch +3, AL N, LV 4",
		},
		{
			"name":      "LICH",
			"tags":      "undead",
			"level":     "13",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "spell",
			"page":      "230",
			"statblock": "AC 16, HP 62, ATK 2 touch +6 (2d8 + paralysis) and 2 spell +7, MV near, S +3, D +1, C +4, I +4, W+3, Ch +3, AL C, LV 13",
		},
		{
			"name":      "LION",
			"tags":      "animal",
			"level":     "3",
			"biome":     "grassland,mountain,river/coast",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "231",
			"statblock": "AC 12, HP 15, ATK 2 rend +4 (1d8), MV near, S +4, D +2, C +2, I -3, W+1, Ch -3, AL N, LV 3",
		},
		{
			"name":      "LIZARDFOLK",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "cave,deeps,desert,jungle,river/coast,swamp",
			"alignment": "C",
			"move":      "swim",
			"attack":    "",
			"page":      "231",
			"statblock": "AC 14 (leather + shield), HP 11, ATK 1 spear (close/near) +2 (1d6), MV near (swim), S +1, D +1, C +2, I-1, W +1, Ch -2, AL C, LV 2",
		},
		{
			"name":      "MAGE",
			"tags":      "humanoid",
			"level":     "6",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "spell",
			"page":      "231",
			"statblock": "AC 11, HP 27, ATK 1 spell +5, MV near, S -1, D +1, C +0, I +3, W +1, Ch+0, AL L, LV 6",
		},
		{
			"name":      "MAMMOTH",
			"tags":      "animal",
			"level":     "9",
			"biome":     "arctic,grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "231",
			"statblock": "AC 15, HP 44, ATK 2 tusks +7 (1d12), MV near, S +5, D +0, C +4, I-2, W +1, Ch +0, AL N, LV 9",
		},
		{
			"name":      "MANTA RAY, GIANT",
			"tags":      "animal,giant",
			"level":     "8",
			"biome":     "ocean",
			"alignment": "N",
			"move":      "swim",
			"attack":    "poison",
			"page":      "232",
			"statblock": "AC 13, HP 37, ATK 2 sting +5 (1d12 + poison), MV double near (swim), S +3, D +3, C +1, I -2, W +1, Ch -3, AL N, LV 8",
		},
		{
			"name":      "MANTICORE",
			"tags":      "monstrosity",
			"level":     "6",
			"biome":     "cave,desert,grassland,mountain",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "232",
			"statblock": "AC 14, HP 29, ATK 2 rend +6 (2d6) or 2 tail spike (far) +4 (1d8), MV double near (fly), S +4, D +2, C +2, I -2, W +1, Ch -2, AL C, LV 6",
		},
		{
			"name":      "MASTIFF",
			"tags":      "animal",
			"level":     "1",
			"biome":     "desert,forest,grassland,river/coast",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "232",
			"statblock": "AC 11, HP 4, ATK 1 bite +1 (1d6), MV near, S +1, D +1, C +0, I -2, W+1, Ch -2, AL N, LV 1",
		},
		{
			"name":      "MEDUSA",
			"tags":      "monstrosity",
			"level":     "8",
			"biome":     "jungle,ruins,swamp,tomb",
			"alignment": "C",
			"move":      "",
			"attack":    "poison",
			"page":      "232",
			"statblock": "AC 14, HP 38, ATK 1 snake bite +6 (1d6 + poison), MV near, S +2, D+1, C +2, I +2, W +3, Ch +4, AL C, LV 8",
		},
		{
			"name":      "MERFOLK",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "ocean",
			"alignment": "L",
			"move":      "swim",
			"attack":    "",
			"page":      "232",
			"statblock": "AC 11, HP 9, ATK 1 spear (close/near) +2 (1d6), MV near (swim), S+1, D +1, C +0, I +0, W +1, Ch +1, AL L, LV 2",
		},
		{
			"name":      "MIMIC",
			"tags":      "monstrosity",
			"level":     "5",
			"biome":     "cave,ruins,tomb",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "232",
			"statblock": "AC 12, HP 23, ATK 2 bite +5 (1d8 + stick), MV near, S +2, D +0, C +1, I-2, W +0, Ch -3, AL N, LV 5",
		},
		{
			"name":      "MINOTAUR",
			"tags":      "monstrosity",
			"level":     "7",
			"biome":     "cave,deeps,mountain,ruins",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "233",
			"statblock": "AC 14 (chainmail), HP 34, ATK 2 greataxe +6 (1d10) and 1 horns +6 (1d12), MV near, S +4, D +1, C +3, I+1, W +2, Ch +1, AL C, LV 7",
		},
		{
			"name":      "MOOSE",
			"tags":      "animal",
			"level":     "4",
			"biome":     "arctic,grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "233",
			"statblock": "AC 11, HP 19, ATK 2 antler +3 (1d6), MV double near, S +3, D +0, C +1, I-2, W +0, Ch -2, AL N, LV 4",
		},
		{
			"name":      "MORDANTICUS THE FLAYED",
			"tags":      "legendary",
			"level":     "19",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "spell",
			"page":      "234",
			"statblock": "AC 17, HP 89, ATK 1 rot touch +8 (1d10 + necrosis) and 3 spell +8, MV near, S +4, D +4, C +4, I +5, W +4, Ch +5, AL N, LV 19",
		},
		{
			"name":      "MUMMY",
			"tags":      "undead",
			"level":     "10",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "236",
			"statblock": "AC 13, HP 47, ATK 3 rot touch +8 (1d10 + necrosis), MV near, S +3, D+0, C +2, I +3, W +2, Ch +3, AL C, LV 10",
		},
		{
			"name":      "MUSHROOMFOLK",
			"tags":      "humanoid,plant",
			"level":     "3",
			"biome":     "cave,deeps,jungle,ruins,swamp",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "236",
			"statblock": "AC 13, HP 15, ATK 2 slam +2 (1d6), MV near, S +2, D -1, C +2, I +0, W+1, Ch +0, AL N, LV 3",
		},
		{
			"name":      "NAGA",
			"tags":      "monstrosity",
			"level":     "9",
			"biome":     "desert,jungle,swamp",
			"alignment": "C",
			"move":      "climb",
			"attack":    "spell,poison",
			"page":      "237",
			"statblock": "AC 16, HP 43, ATK 2 bite +7 (2d6 + poison) and 1 spell +7, MV near (climb), S +4, D +1, C +3, I +2, W+2, Ch +4, AL C, LV 9",
		},
		{
			"name":      "NAGA, BONE",
			"tags":      "monstrosity",
			"level":     "6",
			"biome":     "desert,jungle,ocean,ruins,tomb",
			"alignment": "C",
			"move":      "burrow",
			"attack":    "",
			"page":      "237",
			"statblock": "AC 13, HP 31, ATK 2 bite +5 (2d6), MV near (burrow, climb), S +3, D+2, C +4, I -3, W +0, Ch +4, AL C, LV 6",
		},
		{
			"name":      "NIGHTMARE",
			"tags":      "fiend",
			"level":     "6",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "237",
			"statblock": "AC 13, HP 29, ATK 2 hooves +5 (1d8), MV double near (fly), S +3, D +3, C +2, I -1, W +1, Ch -2, AL C, LV 6",
		},
		{
			"name":      "OBE-IXX OF AZARUMME",
			"tags":      "legendary",
			"level":     "16",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "blood drain",
			"page":      "238",
			"statblock": "AC 18 (+3 plate mail), HP 76, ATK 4 greatsword (near) +11 (1d12 + 2 + Moonbite properties) and 1 bite +9 (1d8 + blood drain) and 1 charm, MV near (climb, fly), S +5, D +3, C +4, I +3, W +4, Ch +5, AL C, LV 16",
		},
		{
			"name":      "OCHRE JELLY",
			"tags":      "ooze",
			"level":     "4",
			"biome":     "cave,ruins,tomb",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "239",
			"statblock": "AC 9, HP 20, ATK 2 tentacle +3 (1d6), MV near (climb), S +2, D -1, C +2, I -4, W -3, Ch -4, AL N, LV 4",
		},
		{
			"name":      "OCTOPUS, GIANT",
			"tags":      "animal,giant",
			"level":     "5",
			"biome":     "ocean",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "239",
			"statblock": "AC 13, HP 23, ATK 2 tentacle (near) +4 (1d8 + grab), MV near (swim), S +3, D +3, C +1, I -2, W +1, Ch -3, AL N, LV 5",
		},
		{
			"name":      "OGRE",
			"tags":      "giant",
			"level":     "6",
			"biome":     "arctic,forest,mountain,ruins,swamp",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "239",
			"statblock": "AC 9, HP 30, ATK 2 greatclub +6 (2d6), MV near, S +4, D -1, C +3, I-2, W -2, Ch -2, AL C, LV 6",
		},
		{
			"name":      "ONI",
			"tags":      "giant",
			"level":     "7",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "spell",
			"page":      "239",
			"statblock": "AC 11, HP 33, ATK 1 glaive (near) +6 (1d10) or 1 spell +5, MV near, S+5, D +1, C +2, I +2, W +1, Ch +3, AL C, LV 7",
		},
		{
			"name":      "ORC",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "240",
			"statblock": "AC 15 (chainmail + shield), HP 4, ATK 1 greataxe +2 (1d8), MV near, S +2, D +0, C +0, I -1, W +0, Ch -1, AL C, LV 1",
		},
		{
			"name":      "ORC, CHIEFTAIN",
			"tags":      "humanoid",
			"level":     "4",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "240",
			"statblock": "AC 14 (chainmail), HP 19, ATK 2 greataxe +4 (1d10), MV near, S +2, D +1, C +1, I -1, W +0, Ch -1, AL C, LV 4",
		},
		{
			"name":      "OTYUGH",
			"tags":      "aberration",
			"level":     "7",
			"biome":     "cave,forest,swamp",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "240",
			"statblock": "AC 13, HP 35, ATK 2 tentacle +5 (1d8) and 1 bite +5 (1d10 + disease), MV near, S +4, D -1, C+4, I -2, W +0, Ch -3, AL N, LV 7",
		},
		{
			"name":      "OWLBEAR",
			"tags":      "monstrosity",
			"level":     "6",
			"biome":     "arctic,forest,ruins",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "242",
			"statblock": "AC 13, HP 30, ATK 2 claw +5 (1d10), MV near (climb), S +4, D +1, C +3, I -2, W +2, Ch -3, AL N, LV 6",
		},
		{
			"name":      "PANTHER",
			"tags":      "animal",
			"level":     "3",
			"biome":     "forest,jungle",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "242",
			"statblock": "AC 14, HP 14, ATK 2 rend +3 (1d6), MV near (climb), S +3, D +4, C +1, I-2, W +1, Ch -3, AL N, LV 3",
		},
		{
			"name":      "PEASANT",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "242",
			"statblock": "AC 10, HP 4, ATK 1 club +0 (1d4), MV near, S +0, D +0, C +0, I +0, W+0, Ch +0, AL L, LV 1",
		},
		{
			"name":      "PEGASUS",
			"tags":      "celestial",
			"level":     "3",
			"biome":     "grassland,mountain,river/coast",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "242",
			"statblock": "AC 12, HP 15, ATK 2 hooves +3 (1d6), MV double near (fly), S +3, D +2, C +2, I -3, W +1, Ch +0, AL N, LV 3",
		},
		{
			"name":      "PHOENIX",
			"tags":      "elemental",
			"level":     "13",
			"biome":     "*",
			"alignment": "L",
			"move":      "fly",
			"attack":    "",
			"page":      "243",
			"statblock": "AC 16, HP 60, ATK 4 rend +8 (2d12), MV double near (fly), S +3, D +4, C +2, I +3, W +3, Ch +3, AL L, LV 13",
		},
		{
			"name":      "PIRANHA, SWARM",
			"tags":      "swarm",
			"level":     "3",
			"biome":     "river/coast",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "243",
			"statblock": "AC 12, HP 13, ATK 2 bite +2 (1d6), MV near (swim), S -2, D +2, C +0, I-3, W +0, Ch -3, AL N, LV 3",
		},
		{
			"name":      "PIRATE",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "ocean,river/coast",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "243",
			"statblock": "AC 12 (leather), HP 4, ATK 1 cutlass +1 (1d6) or 1 dagger (close/near) +1 (1d4), MV near, S +1, D +1, C +0, I +0, W +0, Ch +0, AL C, LV 1",
		},
		{
			"name":      "PLESIOSAURUS",
			"tags":      "dinosaur",
			"level":     "6",
			"biome":     "ocean",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "208",
			"statblock": "AC 13, HP 30, ATK 2 bite +5 (2d8), MV double near (swim), S +4, D +3, C +3, I -3, W +1, Ch -3, AL N, LV 6",
		},
		{
			"name":      "PRIEST",
			"tags":      "humanoid",
			"level":     "5",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "spell",
			"page":      "243",
			"statblock": "AC 15 (chainmail + shield), HP 23, ATK 2 mace +3 (1d6) or 1 spell +3, MV near, S +1, D +0, C +1, I +0, W+2, Ch +1, AL L, LV 5",
		},
		{
			"name":      "PRIMORDIAL SLIME",
			"tags":      "outsider",
			"level":     "6",
			"biome":     "deeps",
			"alignment": "C",
			"move":      "climb",
			"attack":    "",
			"page":      "241",
			"statblock": "AC 9, HP 30, ATK 2 tentacle +4 (1d10 + dissolve), MV near (climb), S +3, D +2, C +3, I -4, W -3, Ch -4, AL C, LV 6",
		},
		{
			"name":      "PTERODACTYL",
			"tags":      "dinosaur",
			"level":     "4",
			"biome":     "grassland,jungle",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "208",
			"statblock": "AC 14, HP 20, ATK 2 beak +4 (1d8 + grab), MV double near (fly), S+2, D +4, C +2, I -2, W +1, Ch -3, AL N, LV 4",
		},
		{
			"name":      "PURPLE WORM",
			"tags":      "monstrosity",
			"level":     "12",
			"biome":     "arctic,deeps,desert",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "poison",
			"page":      "244",
			"statblock": "AC 18, HP 57, ATK 2 bite +9 (2d12 + swallow) and 1 sting +9 (1d10 + poison), MV double near (burrow), S +5, D +1, C +3, I -3, W+1, Ch -3, AL N, LV 12",
		},
		{
			"name":      "RAKSHASA",
			"tags":      "fiend",
			"level":     "8",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "244",
			"statblock": "AC 16, HP 39, ATK 2 claw +6 (1d8), MV near, S +1, D +3, C +3, I +3, W+3, Ch +4, AL C, LV 8",
		},
		{
			"name":      "RAT",
			"tags":      "animal",
			"level":     "0",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "245",
			"statblock": "AC 10, HP 1, ATK 1 bite +0 (1 + disease), MV near, S -3, D +0, C +1, I -3, W +1, Ch -3, AL N, LV 0",
		},
		{
			"name":      "RAT, DIRE",
			"tags":      "animal,dire",
			"level":     "2",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "245",
			"statblock": "AC 12, HP 10, ATK 1 bite +2 (1d6 + disease), MV near, S +1, D +2, C +1, I -2, W +1, Ch -2, AL N, LV 2",
		},
		{
			"name":      "RAT, GIANT",
			"tags":      "animal,giant",
			"level":     "1",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "245",
			"statblock": "AC 11, HP 5, ATK 1 bite +1 (1d4 + disease), MV near, S -2, D +1, C +1, I -2, W +1, Ch -2, AL N, LV 1",
		},
		{
			"name":      "RAT, SWARM",
			"tags":      "animal,swarm",
			"level":     "6",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "245",
			"statblock": "AC 10, HP 28, ATK 4 bite +0 (1 + disease), MV near, S -3, D +0, C +1, I -3, W +1, Ch -3, AL N, LV 6",
		},
		{
			"name":      "RATHGAMNON",
			"tags":      "legendary",
			"level":     "19",
			"biome":     "*",
			"alignment": "L",
			"move":      "fly",
			"attack":    "spell",
			"page":      "246",
			"statblock": "AC 17, HP 89, ATK 2 rend (near) +9 (2d10) and 2 spell +8, MV double near (fly), S +5, D +3, C +4, I +5, W +6, Ch +5, AL L, LV 19",
		},
		{
			"name":      "REAVER",
			"tags":      "humanoid",
			"level":     "6",
			"biome":     "arctic,mountain",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "247",
			"statblock": "AC 17 (plate mail + shield), HP 28, ATK 3 bastard sword +4 (1d8 + 2), MV near, S +3, D +0, C +1, I +0, W+0, Ch +2, AL C, LV 6",
		},
		{
			"name":      "REMORHAZ",
			"tags":      "insect",
			"level":     "10",
			"biome":     "arctic",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "",
			"page":      "247",
			"statblock": "AC 16, HP 47, ATK 3 bite +7 (2d6 + swallow), MV near (burrow), S+5, D +1, C +2, I -3, W +1, Ch -3, AL N, LV 10",
		},
		{
			"name":      "RHINOCEROS",
			"tags":      "animal",
			"level":     "5",
			"biome":     "grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "248",
			"statblock": "AC 14, HP 25, ATK 2 horn +4 (1d8), MV near, S +4, D -1, C +3, I -3, W+0, Ch -3, AL N, LV 5",
		},
		{
			"name":      "RIME WALKER",
			"tags":      "outsider",
			"level":     "9",
			"biome":     "arctic",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "241",
			"statblock": "AC 16, HP 43, ATK 4 claw +8 (1d12), MV near (fly), S +4, D +4, C+3, I +2, W +2, Ch +2, AL C, LV 9",
		},
		{
			"name":      "ROC",
			"tags":      "monstrosity,giant",
			"level":     "15",
			"biome":     "arctic,grassland,mountain",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "248",
			"statblock": "AC 15, HP 69, ATK 4 rend +9 (2d10 + grab), MV double near (fly), S+5, D +3, C +2, I -2, W +2, Ch -2, AL N, LV 15",
		},
		{
			"name":      "ROPER",
			"tags":      "monstrosity",
			"level":     "6",
			"biome":     "deeps",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "248",
			"statblock": "AC 14, HP 31, ATK 4 tendril (double near) +4 (1d6 + grab) and 1 bite +4 (2d8), MV close (climb), S +3, D -2, C +4, I -1, W +2, Ch +1, AL N, LV 6",
		},
		{
			"name":      "ROT FLOWER",
			"tags":      "plant",
			"level":     "2",
			"biome":     "jungle,tomb",
			"alignment": "N",
			"move":      "",
			"attack":    "toxin",
			"page":      "249",
			"statblock": "AC 9, HP 10, ATK 1 bite +1 (1d4 + toxin), MV none, S +1, D -3, C +1, I-4, W -3, Ch -4, AL N, LV 2",
		},
		{
			"name":      "RUST MONSTER",
			"tags":      "monstrosity",
			"level":     "4",
			"biome":     "cave,deeps,desert,ruins,tomb",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "249",
			"statblock": "AC 13, HP 19, ATK 2 claw +3 (1d6), MV near (climb), S +2, D +3, C +1, I-3, W +1, Ch -3, AL N, LV 4",
		},
		{
			"name":      "SAHUAGIN",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "ocean,river/coast",
			"alignment": "C",
			"move":      "swim",
			"attack":    "",
			"page":      "249",
			"statblock": "AC 14 (leather + shield), HP 9, ATK 2 trident (near) +1 (1d6), MV near (swim), S +1, D +1, C +0, I -1, W +0, Ch -1, AL C, LV 2",
		},
		{
			"name":      "SALAMANDER",
			"tags":      "elemental",
			"level":     "5",
			"biome":     "desert,mountain",
			"alignment": "C",
			"move":      "",
			"attack":    "fire",
			"page":      "249",
			"statblock": "AC 13, HP 24, ATK 2 flaming spear (close/near) +4 (1d6, ignites flammables) or 1 iron longbow (far) +2 (1d8), MV near, S +2, D +0, C +2, I -1, W +1, Ch -1, AL C, LV 5",
		},
		{
			"name":      "SCARAB, SWARM",
			"tags":      "insect,swarm",
			"level":     "3",
			"biome":     "desert,ruins,tomb",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "249",
			"statblock": "AC 13, HP 14, ATK 2 bite +3 (1d6), MV near (fly), S -1, D +3, C +1, I -3, W +0, Ch -3, AL N, LV 3",
		},
		{
			"name":      "SCARECROW",
			"tags":      "undead",
			"level":     "3",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "249",
			"statblock": "AC 12, HP 15, ATK 2 claws +2 (1d6) or 1 scream, MV near, S +2, D +2, C +2, I +0, W +0, Ch +2, AL C, LV 3",
		},
		{
			"name":      "SCORPION",
			"tags":      "insect",
			"level":     "0",
			"biome":     "desert,jungle",
			"alignment": "N",
			"move":      "climb",
			"attack":    "poison",
			"page":      "250",
			"statblock": "AC 11, HP 1, ATK 1 sting +1 (1 + poison), MV near (climb), S -4, D+1, C +0, I -4, W +0, Ch -4, AL N, LV 0",
		},
		{
			"name":      "SCORPION, GIANT",
			"tags":      "insect,giant",
			"level":     "3",
			"biome":     "deeps,desert,jungle",
			"alignment": "N",
			"move":      "climb",
			"attack":    "poison",
			"page":      "250",
			"statblock": "AC 14, HP 13, ATK 1 claw +2 (1d6 + grab) and 1 sting +2 (1d4 + poison), MV near (climb), S +2, D+2, C +0, I -4, W +0, Ch -4, AL N, LV 3",
		},
		{
			"name":      "SHADOW",
			"tags":      "undead",
			"level":     "3",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "250",
			"statblock": "AC 12, HP 15, ATK 2 touch +2 (1d4 + drain), MV near (fly), S -4, D +2, C +2, I -2, W +0, Ch -1, AL C, LV 3",
		},
		{
			"name":      "SHAMBLING MOUND",
			"tags":      "plant",
			"level":     "4",
			"biome":     "forest,swamp",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "251",
			"statblock": "AC 14, HP 20, ATK 2 slam +3 (1d6 + engulf), MV near, S +3, D -2, C+2, I -3, W +0, Ch -3, AL N, LV 4",
		},
		{
			"name":      "SHARK",
			"tags":      "animal",
			"level":     "3",
			"biome":     "ocean",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "251",
			"statblock": "AC 11, HP 15, ATK 1 bite +3 (1d10), MV near (swim), S +3, D +1, C +2, I-3, W +1, Ch -3, AL N, LV 3",
		},
		{
			"name":      "SHARK, MEGALODON",
			"tags":      "dinosaur",
			"level":     "8",
			"biome":     "ocean",
			"alignment": "N",
			"move":      "swim",
			"attack":    "",
			"page":      "251",
			"statblock": "AC 13, HP 38, ATK 3 bite +7 (2d8), MV double near (swim), S +5, D +1, C +2, I -3, W +1, Ch -3, AL N, LV 8",
		},
		{
			"name":      "SIREN",
			"tags":      "fey",
			"level":     "4",
			"biome":     "ocean",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "251",
			"statblock": "AC 12, HP 18, ATK 2 claw +2 (1d6) or 1 song, MV near (swim, fly), S+0, D +2, C +0, I +2, W +2, Ch +4, AL C, LV 4",
		},
		{
			"name":      "SKELETON",
			"tags":      "undead",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "251",
			"statblock": "AC 13 (chainmail), HP 11, ATK 1 shortsword +1 (1d6) or 1 shortbow (far) +0 (1d4), MV near, S +1, D +0, C +2, I -2, W +0, Ch -1, AL C, LV 2",
		},
		{
			"name":      "SMILODON",
			"tags":      "animal",
			"level":     "3",
			"biome":     "arctic,grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "251",
			"statblock": "AC 12, HP 14, ATK 2 bite +3 (1d6), MV near, S +3, D +2, C +1, I -3, W+1, Ch -3, AL N, LV 3",
		},
		{
			"name":      "SNAKE, COBRA",
			"tags":      "animal",
			"level":     "1",
			"biome":     "desert",
			"alignment": "N",
			"move":      "",
			"attack":    "poison",
			"page":      "252",
			"statblock": "AC 12, HP 4, ATK 1 bite +2 (1 + poison), MV near, S -3, D +2, C +0, I -3, W +0, Ch -3, AL N, LV 1",
		},
		{
			"name":      "SNAKE, GIANT",
			"tags":      "animal,giant",
			"level":     "5",
			"biome":     "cave,desert,forest,grassland,jungle,river/coast,swamp",
			"alignment": "N",
			"move":      "climb",
			"attack":    "",
			"page":      "252",
			"statblock": "AC 12, HP 23, ATK 2 bite +4 (1d6) and 1 constrict (near), MV near (climb), S +3, D +2, C +1, I -2, W +0, Ch -2, AL N, LV 5",
		},
		{
			"name":      "SNAKE, SWARM",
			"tags":      "animal,swarm",
			"level":     "4",
			"biome":     "jungle,river/coast,swamp",
			"alignment": "N",
			"move":      "",
			"attack":    "poison",
			"page":      "252",
			"statblock": "AC 12, HP 19, ATK 3 bite +2 (1d4 + poison), MV near, S -3, D +2, C +1, I -3, W +0, Ch -3, AL N, LV 4",
		},
		{
			"name":      "SOLDIER",
			"tags":      "humanoid",
			"level":     "2",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "252",
			"statblock": "AC 15 (chainmail + shield), HP10, ATK 1 longsword +2 (1d8) or 1 crossbow (far) +1 (1d6), MV near, S +1, D +0, C +1, I +0, W +0, Ch +0, AL L, LV 2",
		},
		{
			"name":      "SPHINX",
			"tags":      "monstrosity",
			"level":     "9",
			"biome":     "desert,jungle",
			"alignment": "L",
			"move":      "fly",
			"attack":    "spell",
			"page":      "253",
			"statblock": "AC 16, HP 42, ATK 3 claw +7 (1d10) or 2 spell +5, MV double near (fly), S +4, D +1, C +2, I +4, W+4, Ch +3, AL L, LV 9",
		},
		{
			"name":      "SPIDER",
			"tags":      "insect",
			"level":     "0",
			"biome":     "*",
			"alignment": "N",
			"move":      "climb",
			"attack":    "poison",
			"page":      "254",
			"statblock": "AC 11, HP 1, ATK 2 bite +1 (1 + poison), MV near (climb), S -4, D+1, C +0, I -4, W +0, Ch -4, AL N, LV 0",
		},
		{
			"name":      "SPIDER, GIANT",
			"tags":      "insect,giant",
			"level":     "3",
			"biome":     "arctic,cave,deeps,desert,forest,jungle,ruins",
			"alignment": "N",
			"move":      "climb",
			"attack":    "poison",
			"page":      "254",
			"statblock": "AC 13, HP 13, ATK 1 bite +3 (1d4 + poison), MV near (climb), S +2, D +3, C +0, I -2, W +1, Ch -2, AL N, LV 3",
		},
		{
			"name":      "SPIDER, SWARM",
			"tags":      "insect,swarm",
			"level":     "2",
			"biome":     "cave,forest,jungle,ruins,tomb",
			"alignment": "N",
			"move":      "climb",
			"attack":    "poison",
			"page":      "254",
			"statblock": "AC 13, HP 9, ATK 1 bite +3 (1d4 + poison), MV near (climb), S -1, D+3, C +0, I -3, W +1, Ch -3, AL N, LV 2",
		},
		{
			"name":      "STINGBAT",
			"tags":      "animal",
			"level":     "1",
			"biome":     "cave,forest,jungle,river/coast",
			"alignment": "N",
			"move":      "fly",
			"attack":    "blood drain",
			"page":      "254",
			"statblock": "AC 12, HP 4, ATK 1 beak +2 (1d4 + blood drain), MV near (fly), S -2, D +2, C +0, I -2, W +0, Ch -2, AL N, LV 1",
		},
		{
			"name":      "STRANGLER",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "deeps,ruins",
			"alignment": "C",
			"move":      "climb",
			"attack":    "",
			"page":      "254",
			"statblock": "AC 12, HP 14, ATK 2 claws +2 (1d6), MV near (climb), S -2, D +2, C +1, I -2, W +0, Ch -2, AL C, LV 3",
		},
		{
			"name":      "THE TARRASQUE",
			"tags":      "legendary",
			"level":     "30",
			"biome":     "*",
			"alignment": "N",
			"move":      "burrow",
			"attack":    "",
			"page":      "256",
			"statblock": "AC 22, HP 140, ATK 4 thrash (near) +13 (3d10 + sever) and 1 bite (near) +13 (5d10 + sever + swallow), MV triple near (burrow, swim), S +7, D +2, C +5, I -3, W +1, Ch -3, AL N, LV 30",
		},
		{
			"name":      "THE TEN-EYED ORACLE",
			"tags":      "legendary",
			"level":     "18",
			"biome":     "deeps",
			"alignment": "C",
			"move":      "fly",
			"attack":    "",
			"page":      "255",
			"statblock": "AC 17, HP 85, ATK 2d4 eyestalk ray, MV near (fly), S +4, D +5, C +4, I +5, W +4, Ch +4, AL C, LV 18",
		},
		{
			"name":      "THE WANDERING MERCHANT",
			"tags":      "legendary",
			"level":     "15",
			"biome":     "*",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "258",
			"statblock": "AC 16 (mithral chainmail), HP 71, ATK 4 +3 vorpal bastard sword +9 (1d10 + lop), MV near, S +3, D +3, C +4, I +3, W +4, Ch +5, AL L, LV 15",
		},
		{
			"name":      "THIEF",
			"tags":      "humanoid",
			"level":     "3",
			"biome":     "*",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "259",
			"statblock": "AC 13 (leather), HP 13, ATK 1 dagger (close/near) +2 (1d4) or 1 shortsword +0 (1d6), MV near, S+0, D +2, C +0, I +0, W +0, Ch +1, AL N, LV 3",
		},
		{
			"name":      "THUG",
			"tags":      "humanoid",
			"level":     "1",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "259",
			"statblock": "AC 13 (leather + shield), HP 4, ATK 1 shortsword +1 (1d6), MV near, S +1, D +0, C +0, I -1, W +1, Ch -1, AL C, LV 1",
		},
		{
			"name":      "TREANT",
			"tags":      "plant",
			"level":     "8",
			"biome":     "arctic,forest,jungle,mountain",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "259",
			"statblock": "AC 14, HP 38, ATK 3 slam +8 (1d10) or 1 rock (far) +8 (2d12), MV near, S +4, D -1, C +2, I +2, W +3, Ch +1, AL N, LV 8",
		},
		{
			"name":      "TRICERATOPS",
			"tags":      "dinosaur",
			"level":     "7",
			"biome":     "grassland,jungle",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "208",
			"statblock": "AC 17, HP 35, ATK 2 horns +6 (1d10) or 1 charge, MV near, S +4, D -1, C +4, I -3, W +1, Ch -3, AL N, LV 7",
		},
		{
			"name":      "TROLL",
			"tags":      "giant",
			"level":     "5",
			"biome":     "cave,deeps,forest,jungle,mountain,river/coast",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "259",
			"statblock": "AC 12, HP 24, ATK 2 claw +4 (1d6) and 1 bite +4 (1d10), MV near, S+3, D +2, C +2, I -1, W +0, Ch -1, AL C, LV 5",
		},
		{
			"name":      "TROLL, FROST",
			"tags":      "giant",
			"level":     "7",
			"biome":     "arctic",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "260",
			"statblock": "AC 13, HP 34, ATK 2 claw +5 (1d8) and 1 bite +5 (1d12), MV near, S +3, D +2, C +3, I -1, W +0, Ch -1, AL C, LV 7",
		},
		{
			"name":      "TYRANNOSAURUS",
			"tags":      "dinosaur",
			"level":     "9",
			"biome":     "grassland,jungle,swamp",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "208",
			"statblock": "AC 13, HP 44, ATK 3 bite +8 (2d12), MV double near, S +5, D +1, C +4, I -3, W +1, Ch -3, AL N, LV 9",
		},
		{
			"name":      "UNICORN",
			"tags":      "celestial",
			"level":     "4",
			"biome":     "forest,grassland",
			"alignment": "L",
			"move":      "",
			"attack":    "",
			"page":      "260",
			"statblock": "AC 12, HP 20, ATK 1 hooves +3 (1d6), MV double near, S +3, D +2, C +2, I +1, W +2, Ch +3, AL L, LV 4",
		},
		{
			"name":      "VAMPIRE",
			"tags":      "undead",
			"level":     "11",
			"biome":     "*",
			"alignment": "C",
			"move":      "climb",
			"attack":    "blood drain",
			"page":      "260",
			"statblock": "AC 15, HP 52, ATK 3 bite +7 (1d8 + blood drain) or 1 charm, MV near (climb), S +4, D +3, C +3, I +1, W+3, Ch +4, AL C, LV 11",
		},
		{
			"name":      "VAMPIRE SPAWN",
			"tags":      "undead",
			"level":     "5",
			"biome":     "*",
			"alignment": "C",
			"move":      "climb",
			"attack":    "blood drain",
			"page":      "261",
			"statblock": "AC 13 (leather), HP 25, ATK 2 bite +4 (1d8 + blood drain), MV near (climb), S +3, D +2, C +3, I -1, W +1, Ch +2, AL C, LV 5",
		},
		{
			"name":      "VELOCIRAPTOR",
			"tags":      "dinosaur",
			"level":     "2",
			"biome":     "grassland,jungle",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "208",
			"statblock": "AC 13, HP 10, ATK 1 claw +3 (1d6), MV double near, S -1, D +3, C +1, I-2, W +1, Ch -3, AL N, LV 2",
		},
		{
			"name":      "VIOLET FUNGUS",
			"tags":      "plant",
			"level":     "2",
			"biome":     "cave,forest,ruins,tomb",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "261",
			"statblock": "AC 7, HP 9, ATK 2 tendril (near) +0 (1d4), MV close, S -3, D -2, C +0, I -4, W -3, Ch -4, AL N, LV 2",
		},
		{
			"name":      "VIPERIAN",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "jungle",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "262",
			"statblock": "AC 13, HP 13, ATK 2 scimitar +2 (1d6) or 1 javelin (close/far) +2 (1d4), MV near, S +1, D +1, C +0, I+0, W +1, Ch +0, AL C, LV 3",
		},
		{
			"name":      "VIPERIAN OPHID",
			"tags":      "monstrosity",
			"level":     "6",
			"biome":     "jungle",
			"alignment": "C",
			"move":      "climb",
			"attack":    "",
			"page":      "262",
			"statblock": "AC 14, HP 28, ATK 3 falchion +5 (1d10) or 2 longbow (far) +3 (1d8), MV near (climb), S +4, D +2, C +1, I+1, W +1, Ch +1, AL C, LV 6",
		},
		{
			"name":      "VIPERIAN WIZARD",
			"tags":      "monstrosity",
			"level":     "8",
			"biome":     "jungle",
			"alignment": "C",
			"move":      "",
			"attack":    "spell",
			"page":      "262",
			"statblock": "AC 13, HP 37, ATK 1 dagger (close/near) +2 (1d4) or 2 spell +5, MV near, S +0, D +1, C +0, I +3, W +1, Ch +1, AL C, LV 8",
		},
		{
			"name":      "VOID SPAWN",
			"tags":      "outsider",
			"level":     "7",
			"biome":     "deeps",
			"alignment": "C",
			"move":      "fly",
			"attack":    "toxin",
			"page":      "241",
			"statblock": "AC 13, HP 34, ATK 2 scythe +6 (1d10) and 1 tentacles (1d12 + toxin), MV near (fly), S +4, D +1, C+3, I +0, W +1, Ch -1, AL C, LV 7",
		},
		{
			"name":      "VOID SPIDER",
			"tags":      "outsider",
			"level":     "5",
			"biome":     "deeps",
			"alignment": "C",
			"move":      "climb",
			"attack":    "poison",
			"page":      "241",
			"statblock": "AC 13, HP 23, ATK 2 bite +4 (1d8 + poison), MV near (climb), S +3, D +3, C +1, I -1, W +1, Ch -2, AL C, LV 5",
		},
		{
			"name":      "VULTURE",
			"tags":      "animal",
			"level":     "1",
			"biome":     "desert",
			"alignment": "N",
			"move":      "fly",
			"attack":    "",
			"page":      "263",
			"statblock": "AC 10, HP 5, ATK 1 tear +1 (1d4), MV near (fly), S +1, D +0, C +1, I -3, W +1, Ch -3, AL N, LV 1",
		},
		{
			"name":      "WASP, GIANT",
			"tags":      "insect,giant",
			"level":     "2",
			"biome":     "forest,ruins",
			"alignment": "N",
			"move":      "fly",
			"attack":    "venom",
			"page":      "263",
			"statblock": "AC 13, HP 9, ATK 1 sting +3 (1d6 + venom), MV near (fly), S +1, D +3, C +0, I -3, W +0, Ch -3, AL N, LV 2",
		},
		{
			"name":      "WERERAT",
			"tags":      "humanoid",
			"level":     "3",
			"biome":     "tomb",
			"alignment": "C",
			"move":      "climb",
			"attack":    "",
			"page":      "263",
			"statblock": "AC 13 (leather), HP 14, ATK 2 bite +2 (1d6), MV near (climb), S +1, D+2, C +1, I -1, W +1, Ch -1, AL C, LV 3",
		},
		{
			"name":      "WEREWOLF",
			"tags":      "humanoid",
			"level":     "4",
			"biome":     "arctic,cave,desert,forest,grassland,jungle,mountain,river/coast,ruins,swamp,tomb",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "263",
			"statblock": "AC 12, HP 20, ATK 2 rend +3 (1d6), MV double near, S +3, D +2, C +2, I +0, W +1, Ch +0, AL C, LV 4",
		},
		{
			"name":      "WIGHT",
			"tags":      "undead",
			"level":     "3",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "life drain",
			"page":      "263",
			"statblock": "AC 14 (chainmail), HP 15, ATK 1 bastard sword +3 (1d10) and 1 life drain +3, MV near, S +3, D +1, C +2, I +1, W +0, Ch +3, AL C, LV 3",
		},
		{
			"name":      "WILL-O-WISP",
			"tags":      "undead",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "life drain",
			"page":      "264",
			"statblock": "AC 13, HP 10, ATK 1 life drain +3, MV near (fly), S -3, D +3, C +1, I -1, W -1, Ch -2, AL C, LV 2",
		},
		{
			"name":      "WOLF",
			"tags":      "animal",
			"level":     "2",
			"biome":     "desert,forest,grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "264",
			"statblock": "AC 12, HP 10, ATK 1 bite +2 (1d6), MV double near, S +2, D +2, C +1, I-2, W +1, Ch +0, AL N, LV 2",
		},
		{
			"name":      "WOLF, DIRE",
			"tags":      "animal,dire",
			"level":     "4",
			"biome":     "desert,forest,grassland",
			"alignment": "N",
			"move":      "",
			"attack":    "",
			"page":      "264",
			"statblock": "AC 12, HP 19, ATK 2 bite +4 (1d8), MV double near, S +3, D +2, C +1, I-1, W +1, Ch +0, AL N, LV 4",
		},
		{
			"name":      "WOLF, WINTER",
			"tags":      "animal",
			"level":     "5",
			"biome":     "arctic,mountain",
			"alignment": "C",
			"move":      "",
			"attack":    "ice",
			"page":      "264",
			"statblock": "AC 12, HP 23, ATK 2 bite +4 (1d6) or 1 frost breath, MV double near, S +3, D +2, C +1, I +0, W +1, Ch +0, AL C, LV 5",
		},
		{
			"name":      "WORG",
			"tags":      "monstrosity",
			"level":     "3",
			"biome":     "forest,grassland",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "265",
			"statblock": "AC 11, HP 14, ATK 1 bite +3 (1d6), MV double near, S +2, D +1, C +1, I-2, W +1, Ch -2, AL C, LV 3",
		},
		{
			"name":      "WRAITH",
			"tags":      "undead",
			"level":     "8",
			"biome":     "*",
			"alignment": "C",
			"move":      "fly",
			"attack":    "life drain",
			"page":      "265",
			"statblock": "AC 14, HP 36, ATK 3 death touch +6 (1d10 + life drain), MV near (fly), S -4, D +4, C +0, I +0, W +0, Ch +3, AL C, LV 8",
		},
		{
			"name":      "WYVERN",
			"tags":      "dragon",
			"level":     "8",
			"biome":     "arctic,cave,grassland,mountain",
			"alignment": "N",
			"move":      "fly",
			"attack":    "poison",
			"page":      "265",
			"statblock": "AC 15, HP 37, ATK 2 rend +6 (1d8) and 1 stinger +6 (1d6 + poison), MV double near (fly), S +4, D +2, C +1, I -3, W +1, Ch -3, AL N, LV 8",
		},
		{
			"name":      "ZOMBIE",
			"tags":      "undead",
			"level":     "2",
			"biome":     "*",
			"alignment": "C",
			"move":      "",
			"attack":    "",
			"page":      "265",
			"statblock": "AC 8, HP 11, ATK 1 slam +2 (1d6), MV near, S +2, D -2, C +2, I -2, W -2, Ch -3, AL C, LV 2",
		},
	},
}

var cursedScrollMonsters = []map[string]any{
	{
		"name":         "Cursed Scrolls Monster Data",
		"rulesSection": "",
		"description":  "",
		"entries": []map[string]string{
			{
				"name":      "BITTERMOLD",
				"tags":      "humanoid",
				"level":     "1",
				"biome":     "forest,grassland,river/coast,ruins,swamp,tomb",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS1-46",
				"statblock": "AC 12, HP 5, ATK 1 shortsword +1 (1d6) or 1 sling (far) +2 (1d4), MV near, S +1, D +2, C +1, I +0, W +0, Ch +0, AL C, LV 1",
			},
			{
				"name":      "BOGTHORN",
				"tags":      "monstrosity",
				"level":     "2",
				"biome":     "cave,ruins,swamp,tomb",
				"alignment": "C",
				"move":      "climb",
				"attack":    "poison",
				"page":      "CS1-46",
				"statblock": "AC 13, HP 11, ATK 1 stab +0 (1d4) or 1 thorn hail (near) +2 (1d4 + poison), MV near (climb), S +0, D +2, C +2, I -3, W +1, Ch -3, AL C, LV 2",
			},
			{
				"name":      "DRALECH",
				"tags":      "monstrosity",
				"level":     "6",
				"biome":     "cave,ruins,swamp,tomb",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS1-46",
				"statblock": "AC 13, HP 29, ATK 3 bone axe +5 (2d6), MV near, S +4, D +1, C +2, I +0, W +0, Ch +1, AL C, LV 6",
			},
			{
				"name":      "GORDOCK BREEG",
				"tags":      "humanoid",
				"level":     "4",
				"biome":     "forest,grassland,river/coast,ruins,swamp,tomb",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS1-46",
				"statblock": "AC 15 (chainmail), HP 19, ATK 1 bastard sword +3 (1d10) or 1 sling (far) +2 (1d4), MV near, S +3, D +2, C +1, I +1, W +2, Ch +2, AL N, LV 4",
			},
			{
				"name":      "HEXLING",
				"tags":      "fiend",
				"level":     "2",
				"biome":     "cave,ruins,swamp,tomb",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS1-46",
				"statblock": "AC 12, HP 11, ATK 1 chill touch +2 (1d6 + energy drain), MV near, S +0, D +2, C +2, I +0, W +1, Ch +0, AL C, LV 2",
			},
			{
				"name":      "HOWLER",
				"tags":      "humanoid",
				"level":     "1",
				"biome":     "forest,grassland,river/coast,ruins,swamp,tomb",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS1-46",
				"statblock": "AC 15 (leather + shield), HP 5, ATK 1 club +2 (1d4) or 1 sling (far) +2 (1d4), MV near, S +2, D +2, C +1, I +0, W +0, Ch +0, AL N, LV 1",
			},
			{
				"name":      "ICHOR OOZE",
				"tags":      "ooze",
				"level":     "3",
				"biome":     "cave,ruins,swamp,tomb",
				"alignment": "N",
				"move":      "climb",
				"attack":    "",
				"page":      "CS1-47",
				"statblock": "AC 12, HP 15, ATK 2 tendril +3 (1d6), MV near (climb), S +3, D +2, C +2, I -3, W +1, Ch -3, AL N, LV 3",
			},
			{
				"name":      "MARROW FIEND",
				"tags":      "monstrosity",
				"level":     "8",
				"biome":     "forest,grassland,river/coast,ruins,swamp,tomb",
				"alignment": "C",
				"move":      "climb",
				"attack":    "",
				"page":      "CS1-47",
				"statblock": "AC 15, HP 39, ATK 2 claws +7 (1d10) and 1 sap gout (near line) +5 (2d6 + sap), MV near (climb), S +4, D +4, C +3, I +2, W +3, Ch +3, AL C, LV 8",
			},
			{
				"name":      "MUGDULBLUB",
				"tags":      "legendary",
				"level":     "12",
				"biome":     "*",
				"alignment": "C",
				"move":      "climb,swim",
				"attack":    "",
				"page":      "CS1-47",
				"statblock": "AC 16, HP 58, ATK 3 tendril (near) +8 (2d8) and 1 dissolve, MV near (climb, swim), S +5, D +3, C +4, I +2, W +3, Ch +4, AL C, LV 12",
			},
			{
				"name":      "MUTANT CATFISH",
				"tags":      "monstrosity",
				"level":     "2",
				"biome":     "river/coast,ruins,swamp,tomb",
				"alignment": "N",
				"move":      "swim",
				"attack":    "poison",
				"page":      "CS1-47",
				"statblock": "AC 11, HP 11, ATK 1 claw +2 (1d6) or 1 barb (near) +2 (1d4 + poison), MV near (swim), S +2, D +1, C +2, I -2, W +0, Ch -2, AL N, LV 2",
			},
			{
				"name":      "PLOGRINA BITTERMOLD",
				"tags":      "humanoid",
				"level":     "5",
				"biome":     "forest,grassland,river/coast,ruins,swamp,tomb",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS1-48",
				"statblock": "AC 14, HP 25, ATK 2 tendril (near) +4 (1d6), MV near, S +0, D +4, C +3, I +1, W +1, Ch +3, AL C, LV 5",
			},
			{
				"name":      "SKRELL",
				"tags":      "dinosaur",
				"level":     "1",
				"biome":     "forest,grassland,jungle,swamp",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS1-48",
				"statblock": "AC 13, HP 5, ATK 1 claw +2 (1d6), MV double near, S +2, D +3, C +1, I -3, W +1, Ch -3, AL C, LV 1",
			},
			{
				"name":      "TAR BAT",
				"tags":      "monstrosity",
				"level":     "1",
				"biome":     "cave,ruins,swamp,tomb",
				"alignment": "N",
				"move":      "fly",
				"attack":    "",
				"page":      "CS1-48",
				"statblock": "AC 13, HP 4, ATK 1 bite +3 (1d4), MV near (fly), S -3, D +3, C +0, I -3, W +1, Ch -3, AL N, LV 1",
			},
			{
				"name":      "THE WILLOWMAN",
				"tags":      "legendary",
				"level":     "13",
				"biome":     "*",
				"alignment": "C",
				"move":      "teleport",
				"attack":    "",
				"page":      "CS1-48",
				"statblock": "AC 17, HP 61, ATK 3 finger needle +9 (2d10) and 1 terrify, MV near (teleport), S +5, D +7, C +3, I +4, W +4, Ch +5, AL C, LV 13",
			},
			{
				"name":      "CAMEL, SILVER",
				"tags":      "animal",
				"level":     "2",
				"biome":     "desert",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS2-40",
				"statblock": "AC 10, HP 13, ATK 1 hoof +3 (1d6) or 1 spit (near) +0 (1d4), MV double near, S +3, D +0, C +4, I -2, W +1, Ch +0, AL N, LV 2",
			},
			{
				"name":      "CANYON APE",
				"tags":      "animal",
				"level":     "6",
				"biome":     "desert,mountain",
				"alignment": "N",
				"move":      "climb",
				"attack":    "",
				"page":      "CS2-40",
				"statblock": "AC 13, HP 29, ATK 3 rend +6 (2d6), MV near (climb), S +4, D +3, C +2, I -1, W +1, Ch -1, AL N, LV 6",
			},
			{
				"name":      "DONKEY",
				"tags":      "animal",
				"level":     "1",
				"biome":     "desert,forest,grassland,river/coast",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS2-40",
				"statblock": "AC 10, HP 6, ATK 1 hoof +3 (1d4), MV near, S +3, D +0, C +2, I -2, W +1, Ch -2, AL N, LV 1",
			},
			{
				"name":      "DUNEFIEND",
				"tags":      "fiend",
				"level":     "4",
				"biome":     "desert",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS2-40",
				"statblock": "AC 14, HP 20, ATK 2 tear +4 (1d8) or 1 howl, MV near, S +3, D +4, C +2, I +0, W +1, Ch +0, AL C, LV 4",
			},
			{
				"name":      "DUST DEVIL",
				"tags":      "elemental",
				"level":     "8",
				"biome":     "desert",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS2-40",
				"statblock": "AC 16, HP 36, ATK 2 lacerate +5 (2d8), MV double near, S +4, D +4, C +0, I -2, W +0, Ch -2, AL C, LV 8",
			},
			{
				"name":      "HERO, GLADIATOR",
				"tags":      "humanoid",
				"level":     "5",
				"biome":     "*",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS2-41",
				"statblock": "AC 16 (chainmail + shield), HP 25, ATK 3 bastard sword +5 (1d8) or 1 spear (close/near) +5 (1d6), MV near, S +3, D +1, C +3, I +0, W +1, Ch +1, AL N, LV 5",
			},
			{
				"name":      "HORSE, WAR",
				"tags":      "animal",
				"level":     "3",
				"biome":     "*",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS2-41",
				"statblock": "AC 11, HP 15, ATK 1 hooves +4 (1d6), MV double near, S +3, D +1, C +2, I -3, W +1, Ch -1, AL N, LV 3",
			},
			{
				"name":      "MIRAGE",
				"tags":      "fiend",
				"level":     "8",
				"biome":     "*",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS2-41",
				"statblock": "AC 6, HP 32, ATK 1 leech, MV near, S -4, D -4, C -4, I +2, W +1, Ch +4, AL C, LV 8",
			},
			{
				"name":      "RAS-GODAI",
				"tags":      "humanoid",
				"level":     "3",
				"biome":     "desert",
				"alignment": "C",
				"move":      "teleport",
				"attack":    "",
				"page":      "CS2-41",
				"statblock": "AC 13 (leather), HP 13, ATK 1 razor chain (near) +4 (1d6), MV near (teleport), S +1, D +2, C +0, I +0, W +1, Ch +0, AL C, LV 3",
			},
			{
				"name":      "ROOKIE, PIT-FIGHTER",
				"tags":      "humanoid",
				"level":     "1",
				"biome":     "*",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS2-41",
				"statblock": "AC 14 (leather + shield), HP 5, ATK 1 shortsword +1 (1d6) or 1 javelin (close/far) +1 (1d4), MV near, S +1, D +1, C +1, I +0, W +0, Ch +0, AL N, LV 1",
			},
			{
				"name":      "SCRAG",
				"tags":      "monstrosity",
				"level":     "2",
				"biome":     "desert",
				"alignment": "N",
				"move":      "climb",
				"attack":    "",
				"page":      "CS2-43",
				"statblock": "AC 12, HP 11, ATK 1 claw +2 (1d6), MV near (climb), S +2, D +2, C +2, I -2, W +1, Ch -3, AL N, LV 2",
			},
			{
				"name":      "SCRAG, WAR",
				"tags":      "monstrosity",
				"level":     "3",
				"biome":     "desert",
				"alignment": "N",
				"move":      "climb",
				"attack":    "",
				"page":      "CS2-43",
				"statblock": "AC 12, HP 15, ATK 1 claw +3 (1d6), MV near (climb), S +3, D +2, C +2, I -2, W +1, Ch -3, AL N, LV 3",
			},
			{
				"name":      "SIRUUL",
				"tags":      "humanoid",
				"level":     "2",
				"biome":     "desert",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS2-43",
				"statblock": "AC 14 (leather), HP 9, ATK 1 scimitar +3 (1d6) or 1 longbow (far) +3 (1d8), MV double near (mount), S +0, D +3, C +0, I +1, W +1, Ch +1, AL N, LV 2",
			},
			{
				"name":      "THE SCOURGE",
				"tags":      "legendary",
				"level":     "18",
				"biome":     "desert",
				"alignment": "C",
				"move":      "fly",
				"attack":    "electric",
				"page":      "CS2-43",
				"statblock": "AC 17, HP 84, ATK 3 rend +10 (2d10) or lightning breath, MV double near (fly), S +6, D +3, C +3, I +4, W +4, Ch +5, AL C, LV 18",
			},
			{
				"name":      "DRAKE, GREATER",
				"tags":      "dragon",
				"level":     "8",
				"biome":     "arctic,cave,mountain",
				"alignment": "N",
				"move":      "fly",
				"attack":    "fire",
				"page":      "CS3-44",
				"statblock": "AC 15, HP 38, ATK 2 claw +7 (1d12) or 1 fire gout, MV double near (fly), S +4, D +3, C +2, I -2, W +2, Ch +0, AL N, LV 8",
			},
			{
				"name":      "DRAKE, LESSER",
				"tags":      "dragon",
				"level":     "6",
				"biome":     "arctic,cave,mountain",
				"alignment": "N",
				"move":      "fly",
				"attack":    "fire",
				"page":      "CS3-44",
				"statblock": "AC 13, HP 28, ATK 2 claw +5 (1d10) or 1 fire spit, MV double near (fly), S +3, D +2, C +1, I -2, W +1, Ch +0, AL N, LV 6",
			},
			{
				"name":      "DRAUGR",
				"tags":      "undead",
				"level":     "5",
				"biome":     "*",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS3-45",
				"statblock": "AC 16 (chainmail + shield), HP 25, ATK 2 bastard sword +4 (1d8), MV near, S +3, D +1, C +3, I +0, W +0, Ch +3, AL C, LV 5",
			},
			{
				"name":      "DVERG",
				"tags":      "humanoid",
				"level":     "3",
				"biome":     "arctic,cave,deeps,mountain",
				"alignment": "L",
				"move":      "",
				"attack":    "",
				"page":      "CS3-45",
				"statblock": "AC 13 (chainmail), HP 14, ATK 1 greataxe +2 (1d10), MV near, S +2, D +0, C +1, I +1, W +1, Ch +0, AL L, LV 3",
			},
			{
				"name":      "NORD",
				"tags":      "humanoid",
				"level":     "2",
				"biome":     "arctic,ocean,river/coast",
				"alignment": "N",
				"move":      "",
				"attack":    "",
				"page":      "CS3-45",
				"statblock": "AC 15 (chainmail + shield), HP 10, ATK 1 greataxe +2 (1d8) or 1 shield wall, MV near, S +2, D +0, C +1, I +0, W +0, Ch +0, AL N, LV 2",
			},
			{
				"name":      "TROLL, DEEP",
				"tags":      "monstrosity",
				"level":     "8",
				"biome":     "arctic,cave,deeps,mountain",
				"alignment": "C",
				"move":      "",
				"attack":    "",
				"page":      "CS3-46",
				"statblock": "AC 13, HP 39, ATK 2 claw +7 (1d10), MV near, S +4, D +2, C +3, I -1, W +1, Ch +1, AL C, LV 8",
			},
			{
				"name":      "SEA SERPENT",
				"tags":      "monstrosity",
				"level":     "12",
				"biome":     "ocean,river/coast",
				"alignment": "N",
				"move":      "swim",
				"attack":    "",
				"page":      "CS3-46",
				"statblock": "AC 14, HP 58, ATK 3 bite +8 (2d12), MV double near (swim), S +5, D +0, C +4, I -3, W +1, Ch -3, AL N, LV 12",
			},
			{
				"name":      "SEA NYMPH",
				"tags":      "fey",
				"level":     "3",
				"biome":     "ocean,river/coast",
				"alignment": "N",
				"move":      "swim",
				"attack":    "",
				"page":      "CS3-46",
				"statblock": "AC 13, HP 13, ATK 1 slash +2 (1d6) or 1 sing, MV near (swim), S +0, D +3, C +0, I +1, W +1, Ch +2, AL N, LV 3",
			},
			{
				"name":      "ORCA",
				"tags":      "animal",
				"level":     "8",
				"biome":     "ocean,river/coast",
				"alignment": "N",
				"move":      "swim",
				"attack":    "",
				"page":      "CS3-46",
				"statblock": "AC 12, HP 39, ATK 2 bite +5 (1d10), MV double near (swim), S +4, D +0, C +3, I -2, W +1, Ch -2, AL N, LV 8",
			},
			{
				"name":      "ORACLE",
				"tags":      "humanoid",
				"level":     "4",
				"biome":     "*",
				"alignment": "N",
				"move":      "",
				"attack":    "spell",
				"page":      "CS3-46",
				"statblock": "AC 10, HP 19, ATK 1 stave +2 (1d4) or 1 spell +3, MV near, S +1, D +0, C +1, I +0, W +2, Ch +1, AL N, LV 4",
			},
			{
				"name":      "WEREBEAR",
				"tags":      "monstrosity",
				"level":     "7",
				"biome":     "arctic,forest,mountain,river/coast",
				"alignment": "L",
				"move":      "",
				"attack":    "",
				"page":      "CS3-47",
				"statblock": "AC 11, HP 34, ATK 2 claw +6 (1d8), MV near, S +4, D +1, C +3, I +0, W +2, Ch -1, AL L, LV 7",
			},
			{
				"name":      "VALKYRIE",
				"tags":      "celestial",
				"level":     "14",
				"biome":     "*",
				"alignment": "L",
				"move":      "fly",
				"attack":    "",
				"page":      "CS3-47",
				"statblock": "AC 17 (plate mail + shield), HP66, ATK 3 blessed spear (near) +9 (3d6), MV double near (fly), S +4, D +3, C +3, I +3, W +4, Ch +5, AL L, LV 14"},
		},
	},
}
